// Wygenerowano z eksportu Amelia przekazanego przez DerClinic.
// Klucz to login pracownika w DerClinic OS, wartości to dokładne nazwy usług.

export const SPECIALIST_SERVICE_ASSIGNMENTS: Record<string, readonly string[]> = {
  "marta.szyderska": [
    "Modelowanie ust autorską techniką Dr Marty",
    "Hialuronidaza",
    "Topilase® - bezbolesna hialuronidaza w kremie",
    "Peeling TCA Pain Control®",
    "Ellanse® S - autorska technika Dr Marty",
    "Ellanse® M - autorska technika Dr Marty",
    "Lifting podbródka z liposukcją+nici+kwas hialuron.",
    "Plastyka powiek górnych + usunięcie tłuszczu z przegrody oczodołu",
    "Plastyka powiek górnych",
    "Plastyka powiek górnych + usunięcie tłuszczu + lifting brwi",
    "Plastyka powiek dolnych",
    "Toksyna botulinowa - Redukcja uśmiechu dziąsłowego",
    "Toksyna botulinowa - Leczenie migreny",
    "Toksyna botulinowa - 1 okolica",
    "Toksyna botulinowa - 2 okolice",
    "Toksyna botulinowa - 3 okolice",
    "Toksyna botulinowa - 4 okolice",
    "Toksyna botulinowa - Full Face",
    "Toksyna botulinowa - Lifting brwi",
    "Toksyna botulinowa - Leczenie nadpotliwości pachy / dłonie / stopy",
    "Toksyna botulinowa - Zwężenie płatków nosa / podniesienie czubka nosa",
    "Toksyna botulinowa - Lip Flip / broda brukowana / uniesienie kącików ust",
    "Toksyna botulinowa - Leczenie bruksizmu",
    "Podcinanie blizn po trądziku autorską technika",
    "Wolumetria twarzy - autorską techniką dr Marty",
    "Wypełnianie zmarszczek- autorska technika Dr Marty",
    "Kwas polimlekowy Lanluma twarz",
    "Kwas polimlekowy Lanluma pod kontrolą usg (twarz)",
    "Kwas polimlekowy Lanluma twarz i szyja",
    "Kwas polimlekowy Lanluma twarz, szyja i dekolt",
    "Kwas polimlekowy Lanluma pod kontrolą usg (twarz+szyja)",
    "Kwas polimlekowy lanluma - modelowanie pośladków",
    "Kwas polimlekowy Lanluma pod kontrolą usg (twarz+szyja+dekolt)",
    "Hialuronidaza pod kontrolą USG",
    "Nowość! Toksynaa Relfydess - 1 okolica",
    "Nowość! Toksynaa Relfydess - 2 okolice",
    "Nowość! Toksynaa Relfydess - 3 okolice",
    "Rewitalizujące nici PDO autorska technika -20 nici",
    "GOURI ( płynny polikaprolakton) - 1 ml",
    "Kwas hialuronowy autorska technika Dr Marty - 1 ampułka",
    "Kwas hialuronowy autorska technika Dr Marty - 2 ampułki",
    "Kwas hialuronowy autorska technika Dr Marty - 3 ampułki",
    "Specjalistyczna konsultacja u Dr Marty",
    "Laser tulowy twarz + szyja",
    "Laser tulowy na twarz",
    "Laser tulowy na dłonie",
    "Laser tulowy dodatkowy obszar lub przebarwienie",
    "Laser tulowy twarz + szyja + dekolt",
    "Blefaroplastyka powiek górnych",
    "Blefaroplastyka powiek górnych + usunięcie przepuklin tłuszczowych",
    "Blefaroplastyka powiek górnych + lifting brwi",
    "Blefaroplastyka powiek górnych + dolnych + us. przepukliny tłuszczowej",
    "Lipotransfer - powiększanie piersi",
    "Lipotransfer - lifting twarzy",
    "Lipotransfer - lifting pośladków",
    "Plastyka powiek dolnych",
    "Plastyka blizny",
    "Stymulator tkankowy Jalupro Classic + Jalupro HMW",
    "Stymulator tkankowy Jalupro HMW 2 amp",
    "Stymulator tkankowy Jalupro HMW",
    "Stymulator tkankowy Prophilo - molekuła młodości",
    "Stymulator tkankowy Jalupro SuperHydro®",
    "Jalupro SUPERHYDRO - 2 amp",
    "PROFHILO BODY",
    "PROFHILO STRUCTURA",
    "Stymulator tkankowy Radiesse - 1 ampułka",
    "Stymulator tkankowy Radiesse - 2 ampułki",
    "Powtórzenie recepty",
    "Konsultacja + USG leczenie powikłań",
    "Nici stymulujące 20 szt",
    "Nici z kwasu polimlekowego (haczykowe) - dodatkowa nitka",
    "Nici z kwasu polimlekowego (haczykowe) - 4 nitki",
    "Tropokolagen GUNA - 1 ampułka",
    "Tropokolagen GUNA - 2 ampułki",
    "Tropokolagen GUNA - 3 ampułki",
    "Supernowa Nebula Acto2 Orion Strong"
  ],
  "natalia.paryska": [
    "Laser tulowy dodatkowy obszar lub przebarwienie",
    "Laser tulowy twarz + szyja + dekolt",
    "Laser tulowy na twarz",
    "Laser tulowy na dłonie",
    "Laser tulowy twarz + szyja",
    "Supernowa Nebula Acto2 Orion Strong",
    "Peeling medyczny twarz+szyja",
    "Peeling kawitacyjny z doczyszczaniem manualnym",
    "Peeling kawitacyjny z peelingiem kwasowym",
    "Zabieg nawilżający na twarz",
    "Letnie oczyszczanie twarzy",
    "Konsultacja z indywidualnie dobranym zabiegiem",
    "Oczyszczanie manualne z peelingiem kwasowym",
    "HYDRAFACIAL® oryg. oczyszczanie i rewitalizacja - twarz",
    "HYDRAFACIAL® oryg. oczyszczanie i rewitalizacja - twarz + szyja",
    "HYDRAFACIAL® oryg. oczyszczanie i rewitalizacja - twarz + szyja + dekolt",
    "Hydrafacial na plecy",
    "Hydrafacial basic - twarz",
    "Hydrafacial basic - twarz + szyja",
    "Hydrafacial basic - twarz, szyja, dekolt",
    "HYDRAFACIAL® z peelingiem kwaoswym GLYSAL - twarz",
    "HYDRAFACIAL® z peelingiem kwaoswym GLYSAL - twarz + szyja",
    "HYDRAFACIAL® z peelingiem kwaoswym GLYSAL - twarz + szyja + dekolt",
    "Peeling MEDIDERMA® Podstawowy Azelac - twarz/plecy/dekolt",
    "Peeling MEDIDERMA® Podstawowy Azelac - twarz + szyja",
    "Peeling MEDIDERMA® Podstawowy Azelac - twarz + szyja + dekolt",
    "Peeling MEDIDERMA® Podstawowy DNA Recovery - twarz/plecy/dekolt",
    "Peeling MEDIDERMA® Podstawowy DNA Recovery - twarz + szyja",
    "Peeling MEDIDERMA® Podstawowy DNA Recovery - twarz + szyja + dekolt",
    "Peeling MEDIDERMA® Podstawowy Ferulac System - twarz/plecy/dekolt",
    "Peeling MEDIDERMA® Podstawowy Ferulac System - twarz + szyja",
    "Peeling MEDIDERMA® Podstawowy Ferulac System - twarz + szyja + dekolt",
    "Peeling MEDIDERMA® 3-Retises Ct Yellow - twarz/dekolt/plecy",
    "Peeling MEDIDERMA® 3-Retises Ct Yellow - twarz + szyja",
    "Peeling MEDIDERMA® 3-Retises Ct Yellow - twarz + szyja + dekolt",
    "Peeling MEDIDERMA® Podstawowy Ferulac Valencia - twarz/plecy/dekolt",
    "Peeling MEDIDERMA® Podstawowy Ferulac Valencia - twarz + szyja",
    "Peeling MEDIDERMA® Podstawowy Ferulac Valencia - twarz + szyja + dekolt",
    "Peeling MEDIDERMA® Bankietowy z wit.C - twarz/plecy/dekolt",
    "Peeling MEDIDERMA® Bankietowy z wit.C - twarz + szyja",
    "Peeling MEDIDERMA® Bankietowy z wit.C - twarz + szyja + dekolt",
    "Peeling MEDIDERMA® bankietowy liftingujący - twarz/plecy/dekolt",
    "Peeling MEDIDERMA® bankietowy liftingujący - twarz + szyja",
    "Peeling MEDIDERMA® bankietowy liftingujący - twarz + szyja + dekolt",
    "Peeling MEDIDERMA® bankietowy odświeżający - twarz/dekolt/plecy",
    "Peeling MEDIDERMA® bankietowy odświeżający - twarz + szyja",
    "Peeling MEDIDERMA® bankietowy odświeżający - twarz + szyja + dekolt",
    "MedEstelle Redness Sendo Calm Premium - twarz",
    "MedEstelle Redness Sendo Calm Premium twarz+szyja",
    "MedEstelle Redness Senso Calm Premium twarz + szyja + dekolt",
    "MedEstelle Senso Super Hydra Premium twarz",
    "MedEstelle Senso Super Hydra Premium twarz + szyja",
    "MedEstelle Senso Super Hydra Premium twarz + szyja + dekolt",
    "MedEstelle COSMO S-PEEL Vit. C twarz",
    "MedEstelle COSMO S-PEEL Vit. C twarz + szyja",
    "MedEstelle COSMO S-PEEL Vit. C twarz + szyja + dekolt",
    "Lipoliza iniekcyjna - 1 amp",
    "Mezoterapia mezokoktajlami - okolice oczu",
    "Mezoterapia mezokoktajlami - Wybrany obszar",
    "Mezoterapia mezokoktajlami - Twarz",
    "Mezoterapia mezokoktajlami - Skóra głowy",
    "Mezoterapia mezokoktajlami - Twarz + szyja",
    "Mezoterapia mezokoktajlami - Twarz + szyja + dekolt",
    "Osocze bogatopłytkowe PRP - Twarz + szyja",
    "Osocze bogatopłytkowe PRP - Wybrany obszar",
    "Osocze bogatopłytkowe PRP - Twarz + szyja + dekolt",
    "Osocze bogatopłytkowe PRP - Skóra głowy",
    "Osocze bogatopłytkowe PRP - Twarz",
    "Dr Cyj - Hair Filler",
    "Sunekos 200",
    "Stymulator tkankowy Jalupro Classic + Jalupro HMW",
    "Stymulator tkankowy Jalupro HMW 2 amp",
    "Stymulator tkankowy Jalupro HMW",
    "Jalupro mezoterapia aminokwasami - Jalupro Classic® 1 ampułka",
    "Jalupro mezoterapia aminokwasami - Jalupro Classic® 2 ampułki",
    "Jalupro mezoterapia aminokwasami - Jalupro Classic® 3 ampułki",
    "Fibryna bogatopłytkowa - 1 okolica",
    "Fibryna bogatopłytkowa - Więcej niż 1 okolica",
    "Stymulator tkankowy Prophilo - molekuła młodości",
    "Stymulator tkankowy Jalupro Young Eye®",
    "Stymulator tkankowy Jalupro SuperHydro®",
    "Jalupro SUPERHYDRO - 2 amp",
    "SUNEKOS 1200",
    "Xela Rederm 2,2% - 1 ampułka",
    "Xela Rederm 2,2% - 2 ampułki",
    "Xela Rederm 1,1% - 1 ampułka",
    "Xela Rederm 1,1% - 2 ampułki",
    "TwAc EYES",
    "PROFHILO BODY",
    "PROFHILO STRUCTURA",
    "NCTF135 HA Filorga",
    "NANOSOFT EYES BOOSTERS",
    "Stymulator tkankowy Pluryal Silk u P. Magdy",
    "Stymulator tkankowy Pluryal Silk u lekarzy",
    "Mezoterapia Neuvia HYDRO de lux Twarz+szyja 2,5ml",
    "RF Radiofrekwencja mikroigłowa - twarz + szyja",
    "RF Radiofrekwencja mikroigłowa - Okolica oczu",
    "RF Radiofrekwencja mikroigłowa - szyja",
    "RF Radiofrekwencja mikroigłowa - twarz",
    "RF Radiofrekwencja mikroigłowa - twarz + szyja + dekolt",
    "Pakiet 3 zabiegi RF okolica oczu",
    "Pakiet 3 zabiegi RF twarz + szyja dekolt",
    "Pakiet 3 zabiegi RF twarz",
    "Konsultacja kosmetologiczna",
    "Dermapen 4.0® - okolice oczu+ koktaajl filorga NCTF",
    "Dermapen 4.0® - cała twarz + koktaajl filorga NCTF",
    "Dermapen 4.0® - twarz + szyja+ koktaajl filorga NCTF",
    "Dermapen 4.0® - twarz+ szyja + dekolt+ koktaajl filorga NCTF",
    "Dermapen 4.0® + medyczny peeling chemiczny - twarz",
    "Dermapen 4.0® + medyczny peeling chemiczny - twarz + szyja",
    "Dermapen 4.0® + medyczny peeling chemiczny - twarz + szyja + dekolt",
    "Dermapen 4.0 + osocze bogatopłytkowe (twarz + szyja + dekolt + oczy)",
    "DERMAPEN 4.0 + Jalupro twarz",
    "DERMAPEN 4.0 + Jalupro twarz, szyja, dekolt",
    "DERMAPEN 4.0 + Jalupro twarz, szyja",
    "Dermapen + egzosomy (twarz,szyja)",
    "Dermapen + egzosomy (twarz, szyja, dekolt)",
    "Dermapen + egzosomy (twarz)",
    "Dermapen z kwasem tranexamowym (twarz)",
    "Dermapen z kwasem tranexamowym (twarz, szyja)",
    "Dermapen z kwasem tranexamowym (twarz, szyja, dekolt)",
    "Tropokolagen GUNA - 1 ampułka",
    "Tropokolagen GUNA - 3 ampułki",
    "Tropokolagen GUNA - 2 ampułki",
    "Dr Pen okolica oczu + peeling",
    "Odmładzanie z mikronakłuwaniem - twarz + szyja",
    "Odmładzanie z mikronakłuwaniem - twarz + szyja + dekolt",
    "Terapia blizn - Dr Pen + peeling chemiczny Twarz",
    "Terapia blizny - Dr Pen + egzosomy",
    "Supernova Nebula ACTO2 10%",
    "Micropeel",
    "ScarInk Mikronakłuwanie",
    "Konsultacja z kwalifikacją",
    "Makijaż permanentny brwi",
    "Makijaż permanentny ust"
  ],
  "joanna.sankowska": [
    "Supernowa Nebula Acto2 Orion Strong",
    "Regulacja Brwi",
    "Henna pudrowa + regulacja brwi",
    "Laserowe zamykanie naczynka - jedno naczynko",
    "Laserowe zamykanie naczynka - powyżej 3",
    "Laser tulowy dodatkowy obszar lub przebarwienie",
    "Laser tulowy twarz + szyja + dekolt",
    "Laser tulowy na twarz",
    "Laser tulowy na dłonie",
    "Laser tulowy twarz + szyja",
    "Peeling medyczny twarz+szyja",
    "Medyczny peeling skóry głowy",
    "Peeling kawitacyjny z doczyszczaniem manualnym",
    "Peeling kawitacyjny z peelingiem kwasowym",
    "Henna rzęs",
    "Komplet henna rzęsy + brwi",
    "Henna brwi",
    "Męski rytuał pielęgnacyjny",
    "Dodatek - Darsonwal jedna okolica",
    "Dodatek - Maska algowa",
    "Dodatek - Peeling chemiczny",
    "Dodatek - Ampułka",
    "Dodatek - Hydrafacial wstęp do zabiegu",
    "Dodatek - Mikrodermabrazja korundowa do",
    "Dodatek - Peeling kawitacyjny",
    "Dodatek - Regulacja brwi/wąsik/broda",
    "Dodatek - Oczyszczanie manualne",
    "Dodatek - egzosomy Supernova",
    "Dodatek - Wapozon (otworzenie porów)",
    "Dodatek - Henna brwi + regulacja",
    "Dodatek - drenaż limfatyczny na nogi",
    "Zabieg nawilżający na twarz",
    "Letnie oczyszczanie twarzy",
    "Konsultacja z indywidualnie dobranym zabiegiem",
    "Oczyszczanie manualne z peelingiem kwasowym",
    "PRO XN® Przeciwstarzeniowy II stopień z retinolem",
    "PRO XN® Przeciwstarzeniowy I stopień",
    "PRO XN® Przeciwstarzeniowy III stopień + Dermapen",
    "Ksantohumol Recovery Treatment do zabiegu",
    "PRO XN Zabieg rozświetlający BrightUp",
    "ACNE Rescue Treatment",
    "HYDRAFACIAL® z peelingiem kwaoswym GLYSAL - twarz + szyja + dekolt",
    "HYDRAFACIAL® z peelingiem kwaoswym GLYSAL - twarz",
    "HYDRAFACIAL® z peelingiem kwaoswym GLYSAL - twarz + szyja",
    "Hydrafacial basic - twarz + szyja",
    "Hydrafacial basic - twarz, szyja, dekolt",
    "Hydrafacial na plecy",
    "Hydrafacial basic - twarz",
    "HYDRAFACIAL® oryg. oczyszczanie i rewitalizacja - twarz + szyja",
    "HYDRAFACIAL® oryg. oczyszczanie i rewitalizacja - twarz + szyja + dekolt",
    "HYDRAFACIAL® oryg. oczyszczanie i rewitalizacja - twarz",
    "Peeling MEDIDERMA® bankietowy odświeżający - twarz + szyja",
    "Peeling MEDIDERMA® bankietowy odświeżający - twarz + szyja + dekolt",
    "Peeling MEDIDERMA® bankietowy odświeżający - twarz/dekolt/plecy",
    "Peeling MEDIDERMA® bankietowy liftingujący - twarz + szyja",
    "Peeling MEDIDERMA® bankietowy liftingujący - twarz + szyja + dekolt",
    "Peeling MEDIDERMA® bankietowy liftingujący - twarz/plecy/dekolt",
    "Peeling MEDIDERMA® Bankietowy z wit.C - twarz + szyja",
    "Peeling MEDIDERMA® Bankietowy z wit.C - twarz + szyja + dekolt",
    "Peeling MEDIDERMA® Bankietowy z wit.C - twarz/plecy/dekolt",
    "Peeling MEDIDERMA® Podstawowy Ferulac Valencia - twarz + szyja",
    "Peeling MEDIDERMA® Podstawowy Ferulac Valencia - twarz + szyja + dekolt",
    "Peeling MEDIDERMA® Podstawowy Ferulac Valencia - twarz/plecy/dekolt",
    "Peeling MEDIDERMA® 3-Retises Ct Yellow - twarz + szyja",
    "Peeling MEDIDERMA® 3-Retises Ct Yellow - twarz + szyja + dekolt",
    "Peeling MEDIDERMA® 3-Retises Ct Yellow - twarz/dekolt/plecy",
    "Peeling MEDIDERMA® Podstawowy Ferulac System - twarz + szyja",
    "Peeling MEDIDERMA® Podstawowy Ferulac System - twarz + szyja + dekolt",
    "Peeling MEDIDERMA® Podstawowy DNA Recovery - twarz + szyja + dekolt",
    "Peeling MEDIDERMA® Podstawowy Ferulac System - twarz/plecy/dekolt",
    "Peeling MEDIDERMA® Podstawowy DNA Recovery - twarz/plecy/dekolt",
    "Peeling MEDIDERMA® Podstawowy DNA Recovery - twarz + szyja",
    "Peeling MEDIDERMA® Podstawowy Azelac - twarz + szyja",
    "Peeling MEDIDERMA® Podstawowy Azelac - twarz/plecy/dekolt",
    "Peeling MEDIDERMA® Podstawowy Azelac - twarz + szyja + dekolt",
    "MedEstelle COSMO S-PEEL Vit. C twarz + szyja",
    "MedEstelle COSMO S-PEEL Vit. C twarz + szyja + dekolt",
    "MedEstelle Senso Super Hydra Premium twarz + szyja + dekolt",
    "MedEstelle COSMO S-PEEL Vit. C twarz",
    "MedEstelle Senso Super Hydra Premium twarz",
    "MedEstelle Senso Super Hydra Premium twarz + szyja",
    "MedEstelle Redness Sendo Calm Premium twarz+szyja",
    "MedEstelle Redness Senso Calm Premium twarz + szyja + dekolt",
    "MedEstelle Redness Sendo Calm Premium - twarz",
    "Lipoliza iniekcyjna - 1 amp",
    "Mezoterapia mezokoktajlami - okolice oczu",
    "Mezoterapia mezokoktajlami - Wybrany obszar",
    "Mezoterapia mezokoktajlami - Twarz",
    "Mezoterapia mezokoktajlami - Skóra głowy",
    "Mezoterapia mezokoktajlami - Twarz + szyja",
    "Mezoterapia mezokoktajlami - Twarz + szyja + dekolt",
    "Dr Cyj - Hair Filler",
    "Stymulator tkankowy Jalupro Classic + Jalupro HMW",
    "Stymulator tkankowy Jalupro HMW 2 amp",
    "Stymulator tkankowy Jalupro HMW",
    "Jalupro mezoterapia aminokwasami - Jalupro Classic® 3 ampułki",
    "Jalupro mezoterapia aminokwasami - Jalupro Classic® 1 ampułka",
    "Jalupro mezoterapia aminokwasami - Jalupro Classic® 2 ampułki",
    "Stymulator tkankowy Prophilo - molekuła młodości",
    "Xela Rederm 2,2% - 2 ampułki",
    "Xela Rederm 2,2% - 1 ampułka",
    "Xela Rederm 1,1% - 2 ampułki",
    "Xela Rederm 1,1% - 1 ampułka",
    "PROFHILO STRUCTURA",
    "NCTF135 HA Filorga",
    "Stymulator tkankowy Pluryal Silk u P. Magdy",
    "Stymulator tkankowy Pluryal Silk u lekarzy",
    "Mezoterapia Neuvia HYDRO de lux Twarz+szyja 2,5ml",
    "Icoone na twarz (intensywny drenaż liftingujący)",
    "Icoone drenaż limfatyczny - pakiet 10 zabiegów",
    "Icoone drenaż limfatyczny - 1 obszar",
    "Icoone drenaż limfatyczny - 1 obszar pakiet 10 zabiegów",
    "Icoone drenaż limfatyczny - 2 obszary",
    "Icoone drenaż limfatyczny - 2 obszary pakiet 10 zabiegów",
    "Icoone drenaż limfatyczny - 3 obszary",
    "Icoone drenaż limfatyczny - 3 obszary pakiet 10 zabiegów",
    "RF Radiofrekwencja mikroigłowa - Okolica oczu",
    "RF Radiofrekwencja mikroigłowa - szyja",
    "RF Radiofrekwencja mikroigłowa - twarz",
    "Pakiet 3 zabiegi RF okolica oczu",
    "RF Radiofrekwencja mikroigłowa - twarz + szyja",
    "RF Radiofrekwencja mikroigłowa - twarz + szyja + dekolt",
    "Pakiet 3 zabiegi RF twarz",
    "Pakiet 3 zabiegi RF twarz + szyja dekolt",
    "Konsultacja kosmetologiczna",
    "Kontrola",
    "Dermapen 4.0® - okolice oczu+ koktaajl filorga NCTF",
    "Dermapen 4.0® - cała twarz + koktaajl filorga NCTF",
    "Dermapen 4.0® - twarz + szyja+ koktaajl filorga NCTF",
    "Dermapen 4.0® + medyczny peeling chemiczny - twarz",
    "Dermapen 4.0® - twarz+ szyja + dekolt+ koktaajl filorga NCTF",
    "Dermapen 4.0® + medyczny peeling chemiczny - twarz + szyja",
    "Dermapen 4.0® + medyczny peeling chemiczny - twarz + szyja + dekolt",
    "Dermapen z kwasem tranexamowym (twarz)",
    "Dermapen 4.0 + osocze bogatopłytkowe (twarz + szyja + dekolt + oczy)",
    "DERMAPEN 4.0 + Jalupro twarz",
    "Dermapen + egzosomy (twarz)",
    "Dermapen z kwasem tranexamowym (twarz, szyja)",
    "DERMAPEN 4.0 + Jalupro twarz, szyja",
    "Dermapen + egzosomy (twarz,szyja)",
    "Dermapen z kwasem tranexamowym (twarz, szyja, dekolt)",
    "DERMAPEN 4.0 + Jalupro twarz, szyja, dekolt",
    "Dermapen + egzosomy (twarz, szyja, dekolt)",
    "Tropokolagen GUNA - 1 ampułka",
    "Tropokolagen GUNA - 2 ampułki",
    "Tropokolagen GUNA - 3 ampułki",
    "Dr Pen okolica oczu + peeling",
    "Terapia blizn - Dr Pen + peeling chemiczny Twarz",
    "Odmładzanie z mikronakłuwaniem - twarz + szyja",
    "Odmładzanie z mikronakłuwaniem - twarz + szyja + dekolt",
    "Terapia blizny - Dr Pen + egzosomy",
    "Supernova Nebula ACTO2 10%"
  ],
  "anna.krysa": [
    "Iniekcja sterydu",
    "Łyżeczkowanie zmian skórnych",
    "Usunięcie kępek żółtych",
    "Usuwanie zmian w okolicy oczu",
    "Plastyka blizny",
    "Chirurgiczne usunięcie nowotworu skóry",
    "Chirurgiczne usunięcie nowotworu z plastyka miejscową",
    "Biopsja z założeniem szwu chirurgicznego",
    "Laserowe usunięcie zmian skórnych - 1-3 zmian na twarzy",
    "Laserowe usunięcie zmian skórnych - 4-6 zmian na twarzy",
    "Laserowe usunięcie zmian skórnych - >6 zmian na twarzy",
    "Chirurgiczne usunięcie zmiany skórnej - 1 zmiana",
    "Chirurgiczne usunięcie zmiany skórnej - 2-4 zmiany",
    "Chirurgiczne usunięcie zmiany skórnej - 5-7 zmian",
    "Konsultacja chirurgiczna",
    "Badanie histopatologiczne*",
    "Leczenie ran przewlekłych - opracowanie rany",
    "Leczenie ran przewlekłych wraz z konsultacją lek.",
    "Nacięcie i drenaż ropnia",
    "Kontrola",
    "Powtórzenie recepty"
  ],
  "jakub.kobialka": [
    "Laser tulowy na dłonie",
    "Laser tulowy dodatkowy obszar lub przebarwienie",
    "Laser tulowy na twarz",
    "Laser tulowy twarz + szyja",
    "Laser tulowy twarz + szyja + dekolt",
    "Toksyna botulinowa BOTOX - 3 okolice",
    "Toksyna botulinowa BOTOX - 2 okolice",
    "Toksyna botulinowa BOTOX - FULL FACE",
    "Toksyna botulinowa BOTOX - Lip flip / broda brukowana / uniesienie kącika ust",
    "Toksyna botulinowa BOTOX - Bruksizm",
    "Toksyna botulinowa BOTOX - Redukcja uśmiechu dziąsłowego",
    "Toksyna botulinowa BOTOX - 1 okolica",
    "Toksyna botulinowa BOTOX - 4 okolice",
    "Toksyna botulinowa BOTOX - Lifting brwi",
    "Toksyna botulinowa BOTOX - Zwężenie płatków nosa / podniesienie czubka nosa",
    "Toksyna botulinowa BOTOX - Leczenie migreny",
    "Nadpotliwość pachy / dłonie / stopy",
    "Iniekcja sterydu",
    "Łyżeczkowanie zmian skórnych",
    "Konsultacja z dermatoskopią",
    "Leczenie immunomodulujące - łysienie plackowate",
    "Konsultacja dermatologiczna",
    "Dudasteryd - leczenie łysienia androgenowego",
    "Konsultacja trychologiczna",
    "Dermapen stymulacja wzrostu włosów",
    "Usunięcie kępek żółtych",
    "Usuwanie zmian w okolicy oczu",
    "Mezoterapia mezokoktajlami - okolice oczu",
    "Mezoterapia mezokoktajlami - Wybrany obszar",
    "Mezoterapia mezokoktajlami - Skóra głowy",
    "Osocze bogatopłytkowe PRP - Wybrany obszar",
    "Mezoterapia mezokoktajlami - Twarz",
    "NCTF135 HA Filorga",
    "Osocze bogatopłytkowe PRP - Twarz",
    "Mezoterapia mezokoktajlami - Twarz + szyja",
    "Osocze bogatopłytkowe PRP - Skóra głowy",
    "Osocze bogatopłytkowe PRP - Twarz + szyja",
    "Dr Cyj - Hair Filler",
    "Fibryna bogatopłytkowa - 1 okolica",
    "Osocze bogatopłytkowe PRP - Twarz + szyja + dekolt",
    "Jalupro mezoterapia aminokwasami - Jalupro Classic® 1 ampułka",
    "Stymulator tkankowy Jalupro Young Eye®",
    "TwAc EYES",
    "Mezoterapia mezokoktajlami - Twarz + szyja + dekolt",
    "Xela Rederm 1,1% - 1 ampułka",
    "Mezoterapia Neuvia HYDRO de lux Twarz+szyja 2,5ml",
    "Sunekos 200",
    "Stymulator tkankowy Jalupro HMW",
    "Fibryna bogatopłytkowa - Więcej niż 1 okolica",
    "Xela Rederm 2,2% - 1 ampułka",
    "Stymulator tkankowy Pluryal Silk u P. Magdy",
    "Stymulator tkankowy Prophilo - molekuła młodości",
    "Jalupro mezoterapia aminokwasami - Jalupro Classic® 2 ampułki",
    "Stymulator tkankowy Pluryal Silk u lekarzy",
    "SUNEKOS 1200",
    "Stymulator tkankowy Jalupro SuperHydro®",
    "Stymulator tkankowy Jalupro Classic + Jalupro HMW",
    "Xela Rederm 1,1% - 2 ampułki",
    "Jalupro mezoterapia aminokwasami - Jalupro Classic® 3 ampułki",
    "Xela Rederm 2,2% - 2 ampułki",
    "Stymulator tkankowy Jalupro HMW 2 amp",
    "Badanie histopatologiczne*",
    "Leczenie ran przewlekłych - opracowanie rany",
    "Nacięcie i drenaż ropnia",
    "Chirurgiczne usunięcie zmiany skórnej - 1 zmiana",
    "Laserowe usunięcie zmian skórnych - 1-3 zmian na twarzy",
    "Laserowe usunięcie zmian skórnych - 4-6 zmian na twarzy",
    "Biopsja z założeniem szwu chirurgicznego",
    "Chirurgiczne usunięcie zmiany skórnej - 2-4 zmiany",
    "Leczenie ran przewlekłych wraz z konsultacją lek.",
    "Chirurgiczne usunięcie nowotworu skóry",
    "Laserowe usunięcie zmian skórnych - >6 zmian na twarzy",
    "Chirurgiczne usunięcie nowotworu z plastyka miejscową",
    "Chirurgiczne usunięcie zmiany skórnej - 5-7 zmian",
    "Konsultacja lekarza medycyny estetycznej",
    "Konsultacja dermatologiczna",
    "Kontrola",
    "Powtórzenie recepty",
    "Tropokolagen GUNA - 1 ampułka",
    "Tropokolagen GUNA - 2 ampułki",
    "Tropokolagen GUNA - 3 ampułki"
  ],
  "eliza.galinska": [
    "Peeling TCA Pain Control®",
    "Hialuronidaza",
    "Topilase® - bezbolesna hialuronidaza w kremie",
    "Podcinanie blizn po trądziku autorską technika",
    "Ellanse® S - autorska technika Dr Marty",
    "GOURI ( płynny polikaprolakton) - 1 ml",
    "Ellanse® M - autorska technika Dr Marty",
    "Laser tulowy na dłonie",
    "Laser tulowy dodatkowy obszar lub przebarwienie",
    "Laser tulowy na twarz",
    "Laser tulowy twarz + szyja",
    "Laser tulowy twarz + szyja + dekolt",
    "Toksyna botulinowa BOTOX - Lip flip / broda brukowana / uniesienie kącika ust",
    "Toksyna botulinowa BOTOX - Redukcja uśmiechu dziąsłowego",
    "Toksyna botulinowa BOTOX - 1 okolica",
    "Toksyna botulinowa BOTOX - Zwężenie płatków nosa / podniesienie czubka nosa",
    "Toksyna botulinowa BOTOX - 2 okolice",
    "Toksyna botulinowa BOTOX - Bruksizm",
    "Nadpotliwość pachy / dłonie / stopy",
    "Toksyna botulinowa BOTOX - 3 okolice",
    "Toksyna botulinowa BOTOX - 4 okolice",
    "Toksyna botulinowa BOTOX - Lifting brwi",
    "Toksyna botulinowa BOTOX - Leczenie migreny",
    "Toksyna botulinowa BOTOX - FULL FACE",
    "Nowość! Toksynaa Relfydess - 1 okolica",
    "Nowość! Toksynaa Relfydess - 2 okolice",
    "Nowość! Toksynaa Relfydess - 3 okolice",
    "Mezobotox",
    "Konsultacja dermatologiczna",
    "Konsultacja z dermatoskopią",
    "Iniekcja sterydu",
    "Konsultacja trychologiczna",
    "Łyżeczkowanie zmian skórnych",
    "Leczenie immunomodulujące - łysienie plackowate",
    "Dudasteryd - leczenie łysienia androgenowego",
    "Peeling fenolowy na twarz",
    "Usuwanie zmian w okolicy oczu",
    "Lipoliza iniekcyjna - 1 amp",
    "Mezoterapia mezokoktajlami - okolice oczu",
    "Mezoterapia mezokoktajlami - Wybrany obszar",
    "Mezoterapia mezokoktajlami - Skóra głowy",
    "Osocze bogatopłytkowe PRP - Wybrany obszar",
    "Mezoterapia mezokoktajlami - Twarz",
    "Osocze bogatopłytkowe PRP - Twarz",
    "Mezoterapia mezokoktajlami - Twarz + szyja",
    "Osocze bogatopłytkowe PRP - Skóra głowy",
    "Osocze bogatopłytkowe PRP - Twarz + szyja",
    "Dr Cyj - Hair Filler",
    "Fibryna bogatopłytkowa - 1 okolica",
    "Osocze bogatopłytkowe PRP - Twarz + szyja + dekolt",
    "Jalupro mezoterapia aminokwasami - Jalupro Classic® 1 ampułka",
    "Stymulator tkankowy Jalupro Young Eye®",
    "Mezoterapia mezokoktajlami - Twarz + szyja + dekolt",
    "Sunekos 200",
    "Stymulator tkankowy Jalupro HMW",
    "Fibryna bogatopłytkowa - Więcej niż 1 okolica",
    "Stymulator tkankowy Prophilo - molekuła młodości",
    "Jalupro mezoterapia aminokwasami - Jalupro Classic® 2 ampułki",
    "Stymulator tkankowy Jalupro Classic + Jalupro HMW",
    "Jalupro mezoterapia aminokwasami - Jalupro Classic® 3 ampułki",
    "Stymulator tkankowy Jalupro HMW 2 amp",
    "Badanie histopatologiczne*",
    "Nacięcie i drenaż ropnia",
    "Chirurgiczne usunięcie zmiany skórnej - 1 zmiana",
    "Laserowe usunięcie zmian skórnych - 1-3 zmian na twarzy",
    "Laserowe usunięcie zmian skórnych - 4-6 zmian na twarzy",
    "Biopsja z założeniem szwu chirurgicznego",
    "Chirurgiczne usunięcie zmiany skórnej - 2-4 zmiany",
    "Laserowe usunięcie zmian skórnych - >6 zmian na twarzy",
    "Chirurgiczne usunięcie zmiany skórnej - 5-7 zmian",
    "Kwas polimlekowy lanluma - Modelowanie pośladków",
    "Kwas polimlekowy lanluma - Twarz",
    "Kwas polimlekowy lanluma - Twarz + szyja",
    "Kwas polimlekowy lanluma - Twarz, szyja i dekolt",
    "Stymulator tkankowy Jalupro SuperHydro®",
    "Jalupro SUPERHYDRO - 2 amp",
    "SUNEKOS 1200",
    "Xela Rederm 2,2% - 2 ampułki",
    "Xela Rederm 2,2% - 1 ampułka",
    "Xela Rederm 1,1% - 2 ampułki",
    "Xela Rederm 1,1% - 1 ampułka",
    "TwAc EYES",
    "PROFHILO BODY",
    "Nowość! GOURI PCL ( polikaprolakton) - 1ml",
    "PROFHILO STRUCTURA",
    "NCTF135 HA Filorga",
    "NANOSOFT EYES BOOSTERS",
    "Stymulator tkankowy Pluryal Silk u P. Magdy",
    "Stymulator tkankowy Pluryal Silk u lekarzy",
    "Stymulator tkankowy Radiesse - 1 ampułka",
    "Stymulator tkankowy Radiesse - 2 ampułki",
    "Kwas hialuronowy - wypełnienie / modelowanie - 2 ampułki",
    "Kwas hialuronowy - wypełnienie / modelowanie - 1 ampułka",
    "Kwas hialuronowy - wypełnienie / modelowanie - 3 ampułki",
    "Teosyal Ultradeep - 1 ampułka",
    "Teosyal Ultradeep - 2 ampullki",
    "Teosyal RHA2 - 1 ampułka",
    "Teosyal RHA2 - 2 ampułki",
    "Teosyal RHA3 - 1 ampułka",
    "Teosyal RHA3 - 2 ampułki",
    "Teosyal RHA4 - 1 ampułka",
    "Teosyal RHA4 - 2 ampułki",
    "Teosyal Redensity II",
    "Konsultacja lekarza medycyny estetycznej",
    "Konsultacja dermatologiczna",
    "Kontrola",
    "Powtórzenie recepty",
    "Tropokolagen GUNA - 1 ampułka",
    "Tropokolagen GUNA - 2 ampułki",
    "Tropokolagen GUNA - 3 ampułki"
  ],
  "ewelina.kumiszcza": [
    "Peeling TCA Pain Control®",
    "Hialuronidaza",
    "Topilase® - bezbolesna hialuronidaza w kremie",
    "Podcinanie blizn po trądziku autorską technika",
    "Rewitalizujące nici PDO autorska technika -20 nici",
    "Ellanse® S - autorska technika Dr Marty",
    "GOURI ( płynny polikaprolakton) - 1 ml",
    "Ellanse® M - autorska technika Dr Marty",
    "Iniekcja sterydu",
    "Łyżeczkowanie zmian skórnych",
    "Laser tulowy na dłonie",
    "Laser tulowy dodatkowy obszar lub przebarwienie",
    "Laser tulowy na twarz",
    "Laser tulowy twarz + szyja",
    "Laser tulowy twarz + szyja + dekolt",
    "Usuwanie zmian w okolicy oczu",
    "Usunięcie kępek żółtych",
    "Plastyka blizny",
    "Lipotransfer - lifting twarzy",
    "Lipotransfer - powiększanie piersi",
    "Lipotransfer - lifting pośladków",
    "Lipoliza iniekcyjna - 1 amp",
    "Mezoterapia mezokoktajlami - okolice oczu",
    "Mezoterapia mezokoktajlami - Wybrany obszar",
    "NANOSOFT EYES BOOSTERS",
    "Mezoterapia mezokoktajlami - Skóra głowy",
    "Osocze bogatopłytkowe PRP - Wybrany obszar",
    "Mezoterapia mezokoktajlami - Twarz",
    "NCTF135 HA Filorga",
    "Osocze bogatopłytkowe PRP - Twarz",
    "Mezoterapia mezokoktajlami - Twarz + szyja",
    "Osocze bogatopłytkowe PRP - Skóra głowy",
    "Osocze bogatopłytkowe PRP - Twarz + szyja",
    "Dr Cyj - Hair Filler",
    "Fibryna bogatopłytkowa - 1 okolica",
    "Osocze bogatopłytkowe PRP - Twarz + szyja + dekolt",
    "Jalupro mezoterapia aminokwasami - Jalupro Classic® 1 ampułka",
    "Stymulator tkankowy Jalupro Young Eye®",
    "TwAc EYES",
    "Mezoterapia mezokoktajlami - Twarz + szyja + dekolt",
    "Xela Rederm 1,1% - 1 ampułka",
    "Mezoterapia Neuvia HYDRO de lux Twarz+szyja 2,5ml",
    "Sunekos 200",
    "Stymulator tkankowy Jalupro HMW",
    "Fibryna bogatopłytkowa - Więcej niż 1 okolica",
    "Xela Rederm 2,2% - 1 ampułka",
    "Stymulator tkankowy Pluryal Silk u P. Magdy",
    "Stymulator tkankowy Prophilo - molekuła młodości",
    "Jalupro mezoterapia aminokwasami - Jalupro Classic® 2 ampułki",
    "Stymulator tkankowy Pluryal Silk u lekarzy",
    "SUNEKOS 1200",
    "Stymulator tkankowy Jalupro SuperHydro®",
    "Stymulator tkankowy Jalupro Classic + Jalupro HMW",
    "Xela Rederm 1,1% - 2 ampułki",
    "Jalupro mezoterapia aminokwasami - Jalupro Classic® 3 ampułki",
    "Nowość! GOURI PCL ( polikaprolakton) - 1ml",
    "PROFHILO STRUCTURA",
    "Kwas polimlekowy lanluma - Twarz",
    "Stymulator tkankowy Radiesse - 1 ampułka",
    "Xela Rederm 2,2% - 2 ampułki",
    "Stymulator tkankowy Jalupro HMW 2 amp",
    "Jalupro SUPERHYDRO - 2 amp",
    "Kwas polimlekowy lanluma - Twarz + szyja",
    "PROFHILO BODY",
    "Stymulator tkankowy Radiesse - 2 ampułki",
    "Kwas polimlekowy lanluma - Twarz, szyja i dekolt",
    "Kwas polimlekowy lanluma - Modelowanie pośladków",
    "Badanie histopatologiczne*",
    "Konsultacja chirurgiczna",
    "Nacięcie i drenaż ropnia",
    "Chirurgiczne usunięcie zmiany skórnej - 1 zmiana",
    "Laserowe usunięcie zmian skórnych - 1-3 zmian na twarzy",
    "Laserowe usunięcie zmian skórnych - 4-6 zmian na twarzy",
    "Biopsja z założeniem szwu chirurgicznego",
    "Chirurgiczne usunięcie zmiany skórnej - 2-4 zmiany",
    "Laserowe usunięcie zmian skórnych - >6 zmian na twarzy",
    "Chirurgiczne usunięcie zmiany skórnej - 5-7 zmian",
    "Toksyna botulinowa BOTOX - Lip flip / broda brukowana / uniesienie kącika ust",
    "Toksyna botulinowa BOTOX - Redukcja uśmiechu dziąsłowego",
    "Toksyna botulinowa BOTOX - 1 okolica",
    "Nowość! Toksynaa Relfydess - 1 okolica",
    "Toksyna botulinowa BOTOX - Zwężenie płatków nosa / podniesienie czubka nosa",
    "Toksyna botulinowa BOTOX - 2 okolice",
    "Toksyna botulinowa BOTOX - Bruksizm",
    "Nadpotliwość pachy / dłonie / stopy",
    "Nowość! Toksynaa Relfydess - 2 okolice",
    "Mezobotox",
    "Toksyna botulinowa BOTOX - 3 okolice",
    "Toksyna botulinowa BOTOX - 4 okolice",
    "Toksyna botulinowa BOTOX - Lifting brwi",
    "Nowość! Toksynaa Relfydess - 3 okolice",
    "Toksyna botulinowa BOTOX - Leczenie migreny",
    "Toksyna botulinowa BOTOX - FULL FACE",
    "Kwas hialuronowy - wypełnienie / modelowanie - 1 ampułka",
    "Teosyal RHA2 - 1 ampułka",
    "Teosyal Redensity II",
    "Teosyal RHA3 - 1 ampułka",
    "Teosyal Ultradeep - 1 ampułka",
    "Teosyal RHA4 - 1 ampułka",
    "Kwas hialuronowy - wypełnienie / modelowanie - 2 ampułki",
    "Teosyal RHA2 - 2 ampułki",
    "Teosyal RHA3 - 2 ampułki",
    "Kwas hialuronowy - wypełnienie / modelowanie - 3 ampułki",
    "Teosyal Ultradeep - 2 ampullki",
    "Teosyal RHA4 - 2 ampułki",
    "Modelowanie ust \"na płasko\"",
    "Modelowanie ust",
    "Konsultacja lekarza medycyny estetycznej",
    "Kontrola",
    "Powtórzenie recepty",
    "Lifting nićmi APTOS®",
    "Nici stymulujące 20 szt",
    "Nici z kwasu polimlekowego (haczykowe) - dodatkowa nitka",
    "Nici z kwasu polimlekowego (haczykowe) - 4 nitki",
    "Tropokolagen GUNA - 1 ampułka",
    "Tropokolagen GUNA - 2 ampułki",
    "Tropokolagen GUNA - 3 ampułki"
  ],
  "michal.swider": [
    "Supernowa Nebula Acto2 Orion Strong",
    "Konsultacja + usg aorty brzusznej i tętnic",
    "Konsultacja + usg doppler kończyn-żył lub tetnic",
    "Skleroterapia",
    "Miniflebektomia",
    "Laserowe usuwanie żylaków - 1 noga",
    "Laserowe usuwanie żylaków - 2 nogi",
    "Kontrola",
    "Powtórzenie recepty",
    "Badanie histopatologiczne*",
    "Leczenie ran przewlekłych - opracowanie rany",
    "Chirurgiczne usunięcie zmiany skórnej - 1 zmiana",
    "Chirurgiczne usunięcie zmiany skórnej - 2-4 zmiany",
    "Leczenie ran przewlekłych wraz z konsultacją lek.",
    "Chirurgiczne usunięcie nowotworu skóry",
    "Chirurgiczne usunięcie nowotworu z plastyka miejscową",
    "Chirurgiczne usunięcie zmiany skórnej - 5-7 zmian",
    "Konsultacja flebologiczna"
  ],
  "aneta.balcerzak": [
    "Masaż karku i głowy",
    "Manualny drenaż limfatyczny",
    "Masaż MADERO - brazylijski antycellulitowy",
    "Tapping twarzy",
    "Masaż kobido - niechirurgiczny masaż liftingujący",
    "Pakiet 10 zabiegów masaż MADERO",
    "Japoński rytuał młodości masaż KOBIDO + PEELING",
    "Antycellulitowy rytuał SPA",
    "Masaż relaksacyjny twarzy, szyi i dekoltu",
    "Regulacja Brwi",
    "Supernowa Nebula Acto2 Orion Strong",
    "Mezoterapia Neuvia HYDRO de lux Twarz+szyja 2,5ml",
    "Sunekos 200",
    "Konsultacja kosmetologiczna",
    "Tropokolagen GUNA - 1 ampułka",
    "Tropokolagen GUNA - 2 ampułki",
    "Tropokolagen GUNA - 3 ampułki",
    "Letnie oczyszczanie twarzy",
    "Konsultacja z indywidualnie dobranym zabiegiem",
    "Zabieg nawilżający na twarz",
    "Męski rytuał pielęgnacyjny",
    "Peeling MEDIDERMA® Podstawowy DNA Recovery - twarz/plecy/dekolt",
    "Peeling MEDIDERMA® Podstawowy Ferulac System - twarz/plecy/dekolt",
    "Peeling MEDIDERMA® Podstawowy Ferulac Valencia - twarz/plecy/dekolt",
    "Peeling MEDIDERMA® bankietowy odświeżający - twarz/dekolt/plecy",
    "Peeling MEDIDERMA® Podstawowy DNA Recovery - twarz + szyja",
    "Peeling MEDIDERMA® Podstawowy Ferulac System - twarz + szyja",
    "Peeling MEDIDERMA® 3-Retises Ct Yellow - twarz/dekolt/plecy",
    "Peeling MEDIDERMA® Podstawowy Ferulac Valencia - twarz + szyja",
    "Peeling MEDIDERMA® Bankietowy z wit.C - twarz/plecy/dekolt",
    "Peeling MEDIDERMA® bankietowy liftingujący - twarz/plecy/dekolt",
    "Peeling MEDIDERMA® bankietowy odświeżający - twarz + szyja",
    "Peeling MEDIDERMA® Podstawowy DNA Recovery - twarz + szyja + dekolt",
    "Peeling MEDIDERMA® Podstawowy Ferulac System - twarz + szyja + dekolt",
    "Peeling MEDIDERMA® 3-Retises Ct Yellow - twarz + szyja",
    "Peeling MEDIDERMA® Podstawowy Ferulac Valencia - twarz + szyja + dekolt",
    "Peeling MEDIDERMA® Bankietowy z wit.C - twarz + szyja",
    "Peeling MEDIDERMA® bankietowy liftingujący - twarz + szyja",
    "Peeling MEDIDERMA® bankietowy odświeżający - twarz + szyja + dekolt",
    "Peeling MEDIDERMA® 3-Retises Ct Yellow - twarz + szyja + dekolt",
    "Peeling MEDIDERMA® Bankietowy z wit.C - twarz + szyja + dekolt",
    "Peeling MEDIDERMA® bankietowy liftingujący - twarz + szyja + dekolt",
    "MedEstelle COSMO S-PEEL Vit. C twarz",
    "MedEstelle COSMO S-PEEL Vit. C twarz + szyja",
    "MedEstelle Senso Super Hydra Premium twarz",
    "MedEstelle Senso Super Hydra Premium twarz + szyja",
    "MedEstelle COSMO S-PEEL Vit. C twarz + szyja + dekolt",
    "MedEstelle Senso Super Hydra Premium twarz + szyja + dekolt",
    "MedEstelle Redness Sendo Calm Premium - twarz",
    "MedEstelle Redness Sendo Calm Premium twarz+szyja",
    "MedEstelle Redness Senso Calm Premium twarz + szyja + dekolt",
    "Dr Pen okolica oczu + peeling",
    "Odmładzanie z mikronakłuwaniem - twarz + szyja",
    "Odmładzanie z mikronakłuwaniem - twarz + szyja + dekolt",
    "Terapia blizny - Dr Pen + egzosomy",
    "Ksantohumol Recovery Treatment do zabiegu",
    "PRO XN® Przeciwstarzeniowy I stopień",
    "PRO XN® Przeciwstarzeniowy II stopień z retinolem",
    "PRO XN Zabieg rozświetlający BrightUp",
    "PRO XN® Przeciwstarzeniowy III stopień + Dermapen",
    "Icoone na twarz (intensywny drenaż liftingujący)",
    "Icoone drenaż limfatyczny - 1 obszar",
    "Icoone drenaż limfatyczny - pakiet 10 zabiegów",
    "Icoone drenaż limfatyczny - 1 obszar pakiet 10 zabiegów",
    "Bandaż Arosha + Masaż Antycellulitowy",
    "Bandaże Arosha lift plus - ujędrnienie i napięcie",
    "Bandaże Arosha No Drain - terapia drenująca",
    "Bandaże AROSHA + presoterapia"
  ],
  "alina.werner": [
    "Peeling TCA Pain Control®",
    "Topilase® - bezbolesna hialuronidaza w kremie",
    "Podcinanie blizn po trądziku autorską technika",
    "Ellanse® S - autorska technika Dr Marty",
    "Ellanse® M - autorska technika Dr Marty",
    "Iniekcja sterydu",
    "Konsultacja trychologiczna",
    "Łyżeczkowanie zmian skórnych",
    "Leczenie immunomodulujące - łysienie plackowate",
    "Peeling fenolowy na twarz",
    "Dudasteryd - leczenie łysienia androgenowego",
    "Dermapen stymulacja wzrostu włosów",
    "Laser tulowy na dłonie",
    "Laser tulowy dodatkowy obszar lub przebarwienie",
    "Laser tulowy na twarz",
    "Laser tulowy twarz + szyja",
    "Laser tulowy twarz + szyja + dekolt",
    "Supernowa Nebula Acto2 Orion Strong",
    "Toksyna botulinowa BOTOX - Lip flip / broda brukowana / uniesienie kącika ust",
    "Toksyna botulinowa BOTOX - Redukcja uśmiechu dziąsłowego",
    "Toksyna botulinowa BOTOX - 1 okolica",
    "Nowość! Toksynaa Relfydess - 1 okolica",
    "Toksyna botulinowa BOTOX - Zwężenie płatków nosa / podniesienie czubka nosa",
    "Toksyna botulinowa BOTOX - 2 okolice",
    "Toksyna botulinowa BOTOX - Bruksizm",
    "Nadpotliwość pachy / dłonie / stopy",
    "Nowość! Toksynaa Relfydess - 2 okolice",
    "Mezobotox",
    "Toksyna botulinowa BOTOX - 3 okolice",
    "Toksyna botulinowa BOTOX - 4 okolice",
    "Toksyna botulinowa BOTOX - Lifting brwi",
    "Nowość! Toksynaa Relfydess - 3 okolice",
    "Toksyna botulinowa BOTOX - Leczenie migreny",
    "Toksyna botulinowa BOTOX - FULL FACE",
    "Konsultacja dermatologiczna u Dr Aliny",
    "Konsultacja z dermatoskopią u Dr Aliny",
    "Usuwanie zmian w okolicy oczu",
    "Usunięcie kępek żółtych",
    "Lipoliza iniekcyjna - 1 amp",
    "NANOSOFT EYES BOOSTERS",
    "Osocze bogatopłytkowe PRP - Wybrany obszar",
    "NCTF135 HA Filorga",
    "Osocze bogatopłytkowe PRP - Twarz",
    "Osocze bogatopłytkowe PRP - Skóra głowy",
    "Osocze bogatopłytkowe PRP - Twarz + szyja",
    "Dr Cyj - Hair Filler",
    "Fibryna bogatopłytkowa - 1 okolica",
    "Osocze bogatopłytkowe PRP - Twarz + szyja + dekolt",
    "Jalupro mezoterapia aminokwasami - Jalupro Classic® 1 ampułka",
    "TwAc EYES",
    "Xela Rederm 1,1% - 1 ampułka",
    "Mezoterapia Neuvia HYDRO de lux Twarz+szyja 2,5ml",
    "Sunekos 200",
    "Stymulator tkankowy Jalupro HMW",
    "Fibryna bogatopłytkowa - Więcej niż 1 okolica",
    "Xela Rederm 2,2% - 1 ampułka",
    "Stymulator tkankowy Pluryal Silk u P. Magdy",
    "Stymulator tkankowy Prophilo - molekuła młodości",
    "Jalupro mezoterapia aminokwasami - Jalupro Classic® 2 ampułki",
    "Stymulator tkankowy Pluryal Silk u lekarzy",
    "SUNEKOS 1200",
    "Stymulator tkankowy Jalupro SuperHydro®",
    "Stymulator tkankowy Jalupro Classic + Jalupro HMW",
    "Xela Rederm 1,1% - 2 ampułki",
    "Jalupro mezoterapia aminokwasami - Jalupro Classic® 3 ampułki",
    "Nowość! GOURI PCL ( polikaprolakton) - 1ml",
    "PROFHILO STRUCTURA",
    "Kwas polimlekowy lanluma - Twarz",
    "Stymulator tkankowy Radiesse - 1 ampułka",
    "Xela Rederm 2,2% - 2 ampułki",
    "Stymulator tkankowy Jalupro HMW 2 amp",
    "Jalupro SUPERHYDRO - 2 amp",
    "Kwas polimlekowy lanluma - Twarz + szyja",
    "PROFHILO BODY",
    "Stymulator tkankowy Radiesse - 2 ampułki",
    "Kwas polimlekowy lanluma - Twarz, szyja i dekolt",
    "Kwas polimlekowy lanluma - Modelowanie pośladków",
    "Kontrola",
    "Powtórzenie recepty",
    "Konsultacja lekarza medycyny estetycznej",
    "Nici z kwasu polimlekowego (haczykowe) - dodatkowa nitka",
    "Lifting nićmi APTOS®",
    "Nici z kwasu polimlekowego (haczykowe) - 4 nitki",
    "Tropokolagen GUNA - 1 ampułka",
    "Tropokolagen GUNA - 2 ampułki",
    "Tropokolagen GUNA - 3 ampułki",
    "Badanie histopatologiczne*",
    "Nacięcie i drenaż ropnia",
    "Chirurgiczne usunięcie zmiany skórnej - 1 zmiana",
    "Laserowe usunięcie zmian skórnych - 1-3 zmian na twarzy",
    "Laserowe usunięcie zmian skórnych - 4-6 zmian na twarzy",
    "Biopsja z założeniem szwu chirurgicznego",
    "Chirurgiczne usunięcie zmiany skórnej - 2-4 zmiany",
    "Laserowe usunięcie zmian skórnych - >6 zmian na twarzy",
    "Chirurgiczne usunięcie zmiany skórnej - 5-7 zmian",
    "Modelowanie ust",
    "Kwas hialuronowy - wypełnienie / modelowanie - 1 ampułka",
    "Teosyal RHA2 - 1 ampułka",
    "Teosyal Redensity II",
    "Teosyal RHA3 - 1 ampułka",
    "Teosyal Ultradeep - 1 ampułka",
    "Teosyal RHA4 - 1 ampułka",
    "Kwas hialuronowy - wypełnienie / modelowanie - 2 ampułki",
    "Teosyal RHA2 - 2 ampułki",
    "Teosyal RHA3 - 2 ampułki",
    "Kwas hialuronowy - wypełnienie / modelowanie - 3 ampułki",
    "Teosyal Ultradeep - 2 ampullki",
    "Teosyal RHA4 - 2 ampułki"
  ],
  "magdalena.krolak": [
    "Dermapen stymulacja wzrostu włosów",
    "Laser tulowy na dłonie",
    "Laser tulowy dodatkowy obszar lub przebarwienie",
    "Laser tulowy na twarz",
    "Laser tulowy twarz + szyja",
    "Laser tulowy twarz + szyja + dekolt",
    "Lipoliza iniekcyjna - 1 amp",
    "Mezoterapia mezokoktajlami - okolice oczu",
    "Mezoterapia mezokoktajlami - Wybrany obszar",
    "NANOSOFT EYES BOOSTERS",
    "Mezoterapia mezokoktajlami - Skóra głowy",
    "Osocze bogatopłytkowe PRP - Wybrany obszar",
    "Mezoterapia mezokoktajlami - Twarz",
    "NCTF135 HA Filorga",
    "Osocze bogatopłytkowe PRP - Twarz",
    "Mezoterapia mezokoktajlami - Twarz + szyja",
    "Osocze bogatopłytkowe PRP - Skóra głowy",
    "Osocze bogatopłytkowe PRP - Twarz + szyja",
    "Dr Cyj - Hair Filler",
    "Fibryna bogatopłytkowa - 1 okolica",
    "Osocze bogatopłytkowe PRP - Twarz + szyja + dekolt",
    "Jalupro mezoterapia aminokwasami - Jalupro Classic® 1 ampułka",
    "Stymulator tkankowy Jalupro Young Eye®",
    "TwAc EYES",
    "Mezoterapia mezokoktajlami - Twarz + szyja + dekolt",
    "Xela Rederm 1,1% - 1 ampułka",
    "Mezoterapia Neuvia HYDRO de lux Twarz+szyja 2,5ml",
    "Sunekos 200",
    "Stymulator tkankowy Jalupro HMW",
    "Fibryna bogatopłytkowa - Więcej niż 1 okolica",
    "Xela Rederm 2,2% - 1 ampułka",
    "Stymulator tkankowy Pluryal Silk u P. Magdy",
    "Stymulator tkankowy Prophilo - molekuła młodości",
    "Jalupro mezoterapia aminokwasami - Jalupro Classic® 2 ampułki",
    "SUNEKOS 1200",
    "Stymulator tkankowy Jalupro SuperHydro®",
    "Stymulator tkankowy Jalupro Classic + Jalupro HMW",
    "Xela Rederm 1,1% - 2 ampułki",
    "Jalupro mezoterapia aminokwasami - Jalupro Classic® 3 ampułki",
    "PROFHILO STRUCTURA",
    "Xela Rederm 2,2% - 2 ampułki",
    "Stymulator tkankowy Jalupro HMW 2 amp",
    "Jalupro SUPERHYDRO - 2 amp",
    "Tropokolagen GUNA - 1 ampułka",
    "Tropokolagen GUNA - 2 ampułki",
    "Tropokolagen GUNA - 3 ampułki",
    "Medyczny peeling skóry głowy",
    "Peeling kawitacyjny z doczyszczaniem manualnym",
    "Peeling medyczny twarz+szyja",
    "Peeling kawitacyjny z peelingiem kwasowym",
    "Peeling MEDIDERMA® Podstawowy Azelac - twarz/plecy/dekolt",
    "Peeling MEDIDERMA® Podstawowy DNA Recovery - twarz/plecy/dekolt",
    "Peeling MEDIDERMA® Podstawowy Ferulac Valencia - twarz/plecy/dekolt",
    "Peeling MEDIDERMA® Podstawowy Azelac - twarz + szyja",
    "Peeling MEDIDERMA® Podstawowy DNA Recovery - twarz + szyja",
    "Peeling MEDIDERMA® 3-Retises Ct Yellow - twarz/dekolt/plecy",
    "Peeling MEDIDERMA® Podstawowy Ferulac Valencia - twarz + szyja",
    "Peeling MEDIDERMA® Podstawowy Azelac - twarz + szyja + dekolt",
    "Peeling MEDIDERMA® Podstawowy DNA Recovery - twarz + szyja + dekolt",
    "Peeling MEDIDERMA® 3-Retises Ct Yellow - twarz + szyja",
    "Peeling MEDIDERMA® Podstawowy Ferulac Valencia - twarz + szyja + dekolt",
    "Peeling MEDIDERMA® 3-Retises Ct Yellow - twarz + szyja + dekolt",
    "RF Radiofrekwencja mikroigłowa - Okolica oczu",
    "RF Radiofrekwencja mikroigłowa - szyja",
    "RF Radiofrekwencja mikroigłowa - twarz",
    "Pakiet 3 zabiegi RF okolica oczu",
    "RF Radiofrekwencja mikroigłowa - twarz + szyja",
    "RF Radiofrekwencja mikroigłowa - twarz + szyja + dekolt",
    "Pakiet 3 zabiegi RF twarz",
    "Pakiet 3 zabiegi RF twarz + szyja dekolt",
    "Dermapen 4.0® - okolice oczu+ koktaajl filorga NCTF",
    "Dermapen 4.0® - cała twarz + koktaajl filorga NCTF",
    "Dermapen 4.0® - twarz + szyja+ koktaajl filorga NCTF",
    "Dermapen 4.0® + medyczny peeling chemiczny - twarz",
    "Dermapen 4.0® - twarz+ szyja + dekolt+ koktaajl filorga NCTF",
    "Dermapen 4.0® + medyczny peeling chemiczny - twarz + szyja",
    "Dermapen 4.0® + medyczny peeling chemiczny - twarz + szyja + dekolt",
    "Dermapen 4.0 + osocze bogatopłytkowe (twarz + szyja + dekolt + oczy)",
    "DERMAPEN 4.0 + Jalupro twarz",
    "Dermapen + egzosomy (twarz)",
    "DERMAPEN 4.0 + Jalupro twarz, szyja",
    "Dermapen + egzosomy (twarz,szyja)",
    "DERMAPEN 4.0 + Jalupro twarz, szyja, dekolt",
    "Dermapen + egzosomy (twarz, szyja, dekolt)"
  ],
  "anna.frydecka": [
    "Supernowa Nebula Acto2 Orion Strong",
    "Cytologia jednowarstwowa LBC (płynna cytologia)",
    "Cytologia ginekologiczna",
    "Cytologia płynna + HPV",
    "Konsultacja ginekologiczna + usg",
    "USG ginekologiczne",
    "USG wczesna ciąża",
    "Założenie wkładki hormonalnej",
    "Założenie wkładki niehormonalnej",
    "Uwrażliwienie łechtaczki kwasem hialuronowym",
    "Rewitalizacja pochwy PRP",
    "Augumentacja punktu G",
    "Labioplastyka",
    "Nadpotliwość okolic pachwin i sromu",
    "Leczenie pochwicy toksyna botulinową",
    "Leczenie wysiłkowego nietrzymania moczu",
    "Konsultacja ginekologiczna",
    "Konsultacja kobiet w ciąży",
    "Powtórzenie recepty"
  ],
  "mateusz.pyrka": [
    "Topilase® - bezbolesna hialuronidaza w kremie",
    "Ellanse® S - autorska technika Dr Marty",
    "Iniekcja sterydu",
    "Łyżeczkowanie zmian skórnych",
    "Laser tulowy na dłonie",
    "Laser tulowy dodatkowy obszar lub przebarwienie",
    "Laser tulowy na twarz",
    "Laser tulowy twarz + szyja",
    "Laser tulowy twarz + szyja + dekolt",
    "Usuwanie zmian w okolicy oczu",
    "Usunięcie kępek żółtych",
    "Plastyka blizny",
    "Lipotransfer - lifting twarzy",
    "Lipotransfer - powiększanie piersi",
    "Lipotransfer - lifting pośladków",
    "Supernowa Nebula Acto2 Orion Strong",
    "Toksyna botulinowa BOTOX - Lip flip / broda brukowana / uniesienie kącika ust",
    "Toksyna botulinowa BOTOX - Redukcja uśmiechu dziąsłowego",
    "Toksyna botulinowa BOTOX - 1 okolica",
    "Nowość! Toksynaa Relfydess - 1 okolica",
    "Toksyna botulinowa BOTOX - Zwężenie płatków nosa / podniesienie czubka nosa",
    "Toksyna botulinowa BOTOX - 2 okolice",
    "Toksyna botulinowa BOTOX - Bruksizm",
    "Nadpotliwość pachy / dłonie / stopy",
    "Nowość! Toksynaa Relfydess - 2 okolice",
    "Mezobotox",
    "Toksyna botulinowa BOTOX - 3 okolice",
    "Toksyna botulinowa BOTOX - 4 okolice",
    "Toksyna botulinowa BOTOX - Lifting brwi",
    "Nowość! Toksynaa Relfydess - 3 okolice",
    "Toksyna botulinowa BOTOX - Leczenie migreny",
    "Toksyna botulinowa BOTOX - FULL FACE",
    "Lipotransfer - powiększenie penisa",
    "Lipoliza iniekcyjna - 1 amp",
    "Mezoterapia mezokoktajlami - okolice oczu",
    "Mezoterapia mezokoktajlami - Wybrany obszar",
    "NANOSOFT EYES BOOSTERS",
    "Mezoterapia mezokoktajlami - Skóra głowy",
    "Osocze bogatopłytkowe PRP - Wybrany obszar",
    "Mezoterapia mezokoktajlami - Twarz",
    "NCTF135 HA Filorga",
    "Osocze bogatopłytkowe PRP - Twarz",
    "Mezoterapia mezokoktajlami - Twarz + szyja",
    "Osocze bogatopłytkowe PRP - Skóra głowy",
    "Osocze bogatopłytkowe PRP - Twarz + szyja",
    "Dr Cyj - Hair Filler",
    "Fibryna bogatopłytkowa - 1 okolica",
    "Osocze bogatopłytkowe PRP - Twarz + szyja + dekolt",
    "Jalupro mezoterapia aminokwasami - Jalupro Classic® 1 ampułka",
    "Stymulator tkankowy Jalupro Young Eye®",
    "TwAc EYES",
    "Mezoterapia mezokoktajlami - Twarz + szyja + dekolt",
    "Xela Rederm 1,1% - 1 ampułka",
    "Mezoterapia Neuvia HYDRO de lux Twarz+szyja 2,5ml",
    "Sunekos 200",
    "Stymulator tkankowy Jalupro HMW",
    "Fibryna bogatopłytkowa - Więcej niż 1 okolica",
    "Xela Rederm 2,2% - 1 ampułka",
    "Stymulator tkankowy Pluryal Silk u P. Magdy",
    "Stymulator tkankowy Prophilo - molekuła młodości",
    "Jalupro mezoterapia aminokwasami - Jalupro Classic® 2 ampułki",
    "Stymulator tkankowy Pluryal Silk u lekarzy",
    "SUNEKOS 1200",
    "Stymulator tkankowy Jalupro SuperHydro®",
    "Stymulator tkankowy Jalupro Classic + Jalupro HMW",
    "Xela Rederm 1,1% - 2 ampułki",
    "Jalupro mezoterapia aminokwasami - Jalupro Classic® 3 ampułki",
    "Nowość! GOURI PCL ( polikaprolakton) - 1ml",
    "PROFHILO STRUCTURA",
    "Kwas polimlekowy lanluma - Twarz",
    "Stymulator tkankowy Radiesse - 1 ampułka",
    "Xela Rederm 2,2% - 2 ampułki",
    "Stymulator tkankowy Jalupro HMW 2 amp",
    "Jalupro SUPERHYDRO - 2 amp",
    "Kwas polimlekowy lanluma - Twarz + szyja",
    "PROFHILO BODY",
    "Stymulator tkankowy Radiesse - 2 ampułki",
    "Kwas polimlekowy lanluma - Twarz, szyja i dekolt",
    "Kwas polimlekowy lanluma - Modelowanie pośladków",
    "Kontrola",
    "Powtórzenie recepty",
    "Konsultacja lekarza medycyny estetycznej",
    "Tropokolagen GUNA - 2 ampułki",
    "Badanie histopatologiczne*",
    "Konsultacja chirurgiczna",
    "Leczenie ran przewlekłych - opracowanie rany",
    "Nacięcie i drenaż ropnia",
    "Chirurgiczne usunięcie zmiany skórnej - 1 zmiana",
    "Laserowe usunięcie zmian skórnych - 1-3 zmian na twarzy",
    "Laserowe usunięcie zmian skórnych - 4-6 zmian na twarzy",
    "Biopsja z założeniem szwu chirurgicznego",
    "Chirurgiczne usunięcie zmiany skórnej - 2-4 zmiany",
    "Leczenie ran przewlekłych wraz z konsultacją lek.",
    "Chirurgiczne usunięcie nowotworu skóry",
    "Laserowe usunięcie zmian skórnych - >6 zmian na twarzy",
    "Chirurgiczne usunięcie nowotworu z plastyka miejscową",
    "Chirurgiczne usunięcie zmiany skórnej - 5-7 zmian"
  ],
  "adrian.skoczylas": [
    "Peeling TCA Pain Control®",
    "Hialuronidaza",
    "Topilase® - bezbolesna hialuronidaza w kremie",
    "Podcinanie blizn po trądziku autorską technika",
    "Rewitalizujące nici PDO autorska technika -20 nici",
    "Ellanse® S - autorska technika Dr Marty",
    "Ellanse® M - autorska technika Dr Marty",
    "Iniekcja sterydu",
    "Laser tulowy na dłonie",
    "Laser tulowy dodatkowy obszar lub przebarwienie",
    "Laser tulowy na twarz",
    "Laser tulowy twarz + szyja",
    "Laser tulowy twarz + szyja + dekolt",
    "Lipoliza iniekcyjna - 1 amp",
    "Mezoterapia mezokoktajlami - okolice oczu",
    "Mezoterapia mezokoktajlami - Wybrany obszar",
    "NANOSOFT EYES BOOSTERS",
    "Mezoterapia mezokoktajlami - Skóra głowy",
    "Osocze bogatopłytkowe PRP - Wybrany obszar",
    "Mezoterapia mezokoktajlami - Twarz",
    "NCTF135 HA Filorga",
    "Osocze bogatopłytkowe PRP - Twarz",
    "Mezoterapia mezokoktajlami - Twarz + szyja",
    "Osocze bogatopłytkowe PRP - Skóra głowy",
    "Osocze bogatopłytkowe PRP - Twarz + szyja",
    "Dr Cyj - Hair Filler",
    "Fibryna bogatopłytkowa - 1 okolica",
    "Osocze bogatopłytkowe PRP - Twarz + szyja + dekolt",
    "Jalupro mezoterapia aminokwasami - Jalupro Classic® 1 ampułka",
    "Stymulator tkankowy Jalupro Young Eye®",
    "TwAc EYES",
    "Mezoterapia mezokoktajlami - Twarz + szyja + dekolt",
    "Xela Rederm 1,1% - 1 ampułka",
    "Mezoterapia Neuvia HYDRO de lux Twarz+szyja 2,5ml",
    "Sunekos 200",
    "Stymulator tkankowy Jalupro HMW",
    "Fibryna bogatopłytkowa - Więcej niż 1 okolica",
    "Xela Rederm 2,2% - 1 ampułka",
    "Stymulator tkankowy Pluryal Silk u P. Magdy",
    "Stymulator tkankowy Prophilo - molekuła młodości",
    "Jalupro mezoterapia aminokwasami - Jalupro Classic® 2 ampułki",
    "Stymulator tkankowy Pluryal Silk u lekarzy",
    "SUNEKOS 1200",
    "Stymulator tkankowy Jalupro SuperHydro®",
    "Stymulator tkankowy Jalupro Classic + Jalupro HMW",
    "Xela Rederm 1,1% - 2 ampułki",
    "Jalupro mezoterapia aminokwasami - Jalupro Classic® 3 ampułki",
    "Nowość! GOURI PCL ( polikaprolakton) - 1ml",
    "PROFHILO STRUCTURA",
    "Kwas polimlekowy lanluma - Twarz",
    "Stymulator tkankowy Radiesse - 1 ampułka",
    "Xela Rederm 2,2% - 2 ampułki",
    "Stymulator tkankowy Jalupro HMW 2 amp",
    "Jalupro SUPERHYDRO - 2 amp",
    "Kwas polimlekowy lanluma - Twarz + szyja",
    "PROFHILO BODY",
    "Stymulator tkankowy Radiesse - 2 ampułki",
    "Kwas polimlekowy lanluma - Twarz, szyja i dekolt",
    "Kwas polimlekowy lanluma - Modelowanie pośladków",
    "Kontrola",
    "Powtórzenie recepty",
    "Konsultacja lekarza medycyny estetycznej",
    "Nici z kwasu polimlekowego (haczykowe) - dodatkowa nitka",
    "Nici stymulujące 20 szt",
    "Lifting nićmi APTOS®",
    "Nici z kwasu polimlekowego (haczykowe) - 4 nitki",
    "Tropokolagen GUNA - 1 ampułka",
    "Tropokolagen GUNA - 2 ampułki",
    "Tropokolagen GUNA - 3 ampułki",
    "Toksyna botulinowa BOTOX - Lip flip / broda brukowana / uniesienie kącika ust",
    "Toksyna botulinowa BOTOX - Redukcja uśmiechu dziąsłowego",
    "Toksyna botulinowa BOTOX - 1 okolica",
    "Nowość! Toksynaa Relfydess - 1 okolica",
    "Toksyna botulinowa BOTOX - Zwężenie płatków nosa / podniesienie czubka nosa",
    "Toksyna botulinowa BOTOX - 2 okolice",
    "Toksyna botulinowa BOTOX - Bruksizm",
    "Nadpotliwość pachy / dłonie / stopy",
    "Nowość! Toksynaa Relfydess - 2 okolice",
    "Mezobotox",
    "Toksyna botulinowa BOTOX - 3 okolice",
    "Toksyna botulinowa BOTOX - 4 okolice",
    "Toksyna botulinowa BOTOX - Lifting brwi",
    "Nowość! Toksynaa Relfydess - 3 okolice",
    "Toksyna botulinowa BOTOX - Leczenie migreny",
    "Toksyna botulinowa BOTOX - FULL FACE",
    "Modelowanie ust",
    "Kwas hialuronowy - wypełnienie / modelowanie - 1 ampułka",
    "Modelowanie ust \"na płasko\"",
    "Teosyal RHA2 - 1 ampułka",
    "Teosyal Redensity II",
    "Teosyal RHA3 - 1 ampułka",
    "Teosyal Ultradeep - 1 ampułka",
    "Teosyal RHA4 - 1 ampułka",
    "Kwas hialuronowy - wypełnienie / modelowanie - 2 ampułki",
    "Teosyal RHA2 - 2 ampułki",
    "Teosyal RHA3 - 2 ampułki",
    "Kwas hialuronowy - wypełnienie / modelowanie - 3 ampułki",
    "Teosyal Ultradeep - 2 ampullki",
    "Teosyal RHA4 - 2 ampułki"
  ],
  "anna.mikolajewska": [
    "Peeling TCA Pain Control®",
    "Hialuronidaza",
    "Topilase® - bezbolesna hialuronidaza w kremie",
    "Podcinanie blizn po trądziku autorską technika",
    "Ellanse® S - autorska technika Dr Marty",
    "Ellanse® M - autorska technika Dr Marty",
    "Iniekcja sterydu",
    "Laser tulowy na dłonie",
    "Laser tulowy dodatkowy obszar lub przebarwienie",
    "Laser tulowy na twarz",
    "Laser tulowy twarz + szyja",
    "Laser tulowy twarz + szyja + dekolt",
    "Usuwanie zmian w okolicy oczu",
    "Usunięcie kępek żółtych",
    "Lipoliza iniekcyjna - 1 amp",
    "NANOSOFT EYES BOOSTERS",
    "Osocze bogatopłytkowe PRP - Wybrany obszar",
    "NCTF135 HA Filorga",
    "Osocze bogatopłytkowe PRP - Twarz",
    "Osocze bogatopłytkowe PRP - Skóra głowy",
    "Osocze bogatopłytkowe PRP - Twarz + szyja",
    "Dr Cyj - Hair Filler",
    "Fibryna bogatopłytkowa - 1 okolica",
    "Osocze bogatopłytkowe PRP - Twarz + szyja + dekolt",
    "Jalupro mezoterapia aminokwasami - Jalupro Classic® 1 ampułka",
    "Stymulator tkankowy Jalupro Young Eye®",
    "TwAc EYES",
    "Xela Rederm 1,1% - 1 ampułka",
    "Mezoterapia Neuvia HYDRO de lux Twarz+szyja 2,5ml",
    "Sunekos 200",
    "Stymulator tkankowy Jalupro HMW",
    "Fibryna bogatopłytkowa - Więcej niż 1 okolica",
    "Xela Rederm 2,2% - 1 ampułka",
    "Stymulator tkankowy Pluryal Silk u P. Magdy",
    "Stymulator tkankowy Prophilo - molekuła młodości",
    "Jalupro mezoterapia aminokwasami - Jalupro Classic® 2 ampułki",
    "Stymulator tkankowy Pluryal Silk u lekarzy",
    "SUNEKOS 1200",
    "Stymulator tkankowy Jalupro SuperHydro®",
    "Stymulator tkankowy Jalupro Classic + Jalupro HMW",
    "Xela Rederm 1,1% - 2 ampułki",
    "Jalupro mezoterapia aminokwasami - Jalupro Classic® 3 ampułki",
    "Nowość! GOURI PCL ( polikaprolakton) - 1ml",
    "PROFHILO STRUCTURA",
    "Kwas polimlekowy lanluma - Twarz",
    "Stymulator tkankowy Radiesse - 1 ampułka",
    "Xela Rederm 2,2% - 2 ampułki",
    "Stymulator tkankowy Jalupro HMW 2 amp",
    "Kwas polimlekowy lanluma - Twarz + szyja",
    "PROFHILO BODY",
    "Stymulator tkankowy Radiesse - 2 ampułki",
    "Kwas polimlekowy lanluma - Twarz, szyja i dekolt",
    "Kwas polimlekowy lanluma - Modelowanie pośladków",
    "Kontrola",
    "Powtórzenie recepty",
    "Konsultacja lekarza medycyny estetycznej",
    "Nici z kwasu polimlekowego (haczykowe) - dodatkowa nitka",
    "Nici stymulujące 20 szt",
    "Lifting nićmi APTOS®",
    "Nici z kwasu polimlekowego (haczykowe) - 4 nitki",
    "Tropokolagen GUNA - 1 ampułka",
    "Tropokolagen GUNA - 2 ampułki",
    "Tropokolagen GUNA - 3 ampułki",
    "Supernowa Nebula Acto2 Orion Strong",
    "Badanie histopatologiczne*",
    "Chirurgiczne usunięcie zmiany skórnej - 1 zmiana",
    "Laserowe usunięcie zmian skórnych - 1-3 zmian na twarzy",
    "Laserowe usunięcie zmian skórnych - 4-6 zmian na twarzy",
    "Chirurgiczne usunięcie zmiany skórnej - 2-4 zmiany",
    "Laserowe usunięcie zmian skórnych - >6 zmian na twarzy",
    "Chirurgiczne usunięcie zmiany skórnej - 5-7 zmian",
    "Toksyna botulinowa BOTOX - Lip flip / broda brukowana / uniesienie kącika ust",
    "Toksyna botulinowa BOTOX - Redukcja uśmiechu dziąsłowego",
    "Toksyna botulinowa BOTOX - 1 okolica",
    "Nowość! Toksynaa Relfydess - 1 okolica",
    "Toksyna botulinowa BOTOX - Zwężenie płatków nosa / podniesienie czubka nosa",
    "Toksyna botulinowa BOTOX - 2 okolice",
    "Toksyna botulinowa BOTOX - Bruksizm",
    "Nadpotliwość pachy / dłonie / stopy",
    "Nowość! Toksynaa Relfydess - 2 okolice",
    "Mezobotox",
    "Toksyna botulinowa BOTOX - 3 okolice",
    "Toksyna botulinowa BOTOX - 4 okolice",
    "Toksyna botulinowa BOTOX - Lifting brwi",
    "Nowość! Toksynaa Relfydess - 3 okolice",
    "Toksyna botulinowa BOTOX - Leczenie migreny",
    "Toksyna botulinowa BOTOX - FULL FACE",
    "Kwas hialuronowy - wypełnienie / modelowanie - 1 ampułka",
    "Teosyal RHA2 - 1 ampułka",
    "Teosyal Redensity II",
    "Teosyal RHA3 - 1 ampułka",
    "Teosyal Ultradeep - 1 ampułka",
    "Teosyal RHA4 - 1 ampułka",
    "Kwas hialuronowy - wypełnienie / modelowanie - 2 ampułki",
    "Teosyal RHA2 - 2 ampułki",
    "Teosyal RHA3 - 2 ampułki",
    "Kwas hialuronowy - wypełnienie / modelowanie - 3 ampułki",
    "Teosyal Ultradeep - 2 ampullki",
    "Teosyal RHA4 - 2 ampułki"
  ],
  "recepcja": [
    "Masaż karku i głowy",
    "Masaż MADERO - brazylijski antycellulitowy",
    "Manualny drenaż limfatyczny",
    "Relaksacyjny masaż pleców",
    "Relaksacyjny masaż całego ciała",
    "Pakiet 10 zabiegów masaż MADERO",
    "Antycellulitowy rytuał SPA",
    "Regulacja Brwi",
    "Supernowa Nebula Acto2 Orion Strong",
    "Konsultacja kosmetologiczna",
    "Tropokolagen GUNA - 1 ampułka",
    "Tropokolagen GUNA - 2 ampułki",
    "Tropokolagen GUNA - 3 ampułki",
    "Letnie oczyszczanie twarzy",
    "Konsultacja z indywidualnie dobranym zabiegiem",
    "Zabieg nawilżający na twarz",
    "Męski rytuał pielęgnacyjny",
    "Peeling MEDIDERMA® Podstawowy Ferulac System - twarz/plecy/dekolt",
    "Peeling MEDIDERMA® bankietowy odświeżający - twarz/dekolt/plecy",
    "Peeling MEDIDERMA® Podstawowy Ferulac System - twarz + szyja",
    "Peeling MEDIDERMA® Bankietowy z wit.C - twarz/plecy/dekolt",
    "Peeling MEDIDERMA® bankietowy liftingujący - twarz/plecy/dekolt",
    "Peeling MEDIDERMA® bankietowy odświeżający - twarz + szyja",
    "Peeling MEDIDERMA® Podstawowy Ferulac System - twarz + szyja + dekolt",
    "Peeling MEDIDERMA® Bankietowy z wit.C - twarz + szyja",
    "Peeling MEDIDERMA® bankietowy liftingujący - twarz + szyja",
    "Peeling MEDIDERMA® bankietowy odświeżający - twarz + szyja + dekolt",
    "Peeling MEDIDERMA® Bankietowy z wit.C - twarz + szyja + dekolt",
    "Peeling MEDIDERMA® bankietowy liftingujący - twarz + szyja + dekolt",
    "MedEstelle COSMO S-PEEL Vit. C twarz",
    "MedEstelle COSMO S-PEEL Vit. C twarz + szyja",
    "MedEstelle Senso Super Hydra Premium twarz",
    "MedEstelle Senso Super Hydra Premium twarz + szyja",
    "MedEstelle COSMO S-PEEL Vit. C twarz + szyja + dekolt",
    "MedEstelle Senso Super Hydra Premium twarz + szyja + dekolt",
    "MedEstelle Redness Sendo Calm Premium - twarz",
    "MedEstelle Redness Sendo Calm Premium twarz+szyja",
    "MedEstelle Redness Senso Calm Premium twarz + szyja + dekolt",
    "Pakiet 3 zabiegi RF twarz",
    "Dr Pen okolica oczu + peeling",
    "Odmładzanie z mikronakłuwaniem - twarz + szyja",
    "Odmładzanie z mikronakłuwaniem - twarz + szyja + dekolt",
    "Terapia blizny - Dr Pen + egzosomy",
    "Ksantohumol Recovery Treatment do zabiegu",
    "PRO XN® Przeciwstarzeniowy I stopień",
    "PRO XN® Przeciwstarzeniowy II stopień z retinolem",
    "PRO XN Zabieg rozświetlający BrightUp",
    "PRO XN® Przeciwstarzeniowy III stopień + Dermapen",
    "Icoone na twarz (intensywny drenaż liftingujący)",
    "Icoone drenaż limfatyczny - 1 obszar",
    "Icoone drenaż limfatyczny - 2 obszary",
    "Icoone drenaż limfatyczny - 3 obszary",
    "Icoone drenaż limfatyczny - pakiet 10 zabiegów",
    "Icoone drenaż limfatyczny - 1 obszar pakiet 10 zabiegów",
    "Icoone drenaż limfatyczny - 2 obszary pakiet 10 zabiegów",
    "Icoone drenaż limfatyczny - 3 obszary pakiet 10 zabiegów",
    "Bandaże Arosha lift plus - ujędrnienie i napięcie",
    "Bandaże Arosha No Drain - terapia drenująca",
    "Bandaże AROSHA + presoterapia",
    "Bandaż Arosha + Masaż Antycellulitowy",
    "Recepcja"
  ],
  "weronika.kaczor": [
    "Kontrola",
    "Powtórzenie recepty",
    "Konsultacja lekarza medycyny estetycznej",
    "Toksyna botulinowa BOTOX - Lip flip / broda brukowana / uniesienie kącika ust",
    "Toksyna botulinowa BOTOX - Redukcja uśmiechu dziąsłowego",
    "Toksyna botulinowa BOTOX - 1 okolica",
    "Nowość! Toksynaa Relfydess - 1 okolica",
    "Toksyna botulinowa BOTOX - Zwężenie płatków nosa / podniesienie czubka nosa",
    "Toksyna botulinowa BOTOX - 2 okolice",
    "Toksyna botulinowa BOTOX - Bruksizm",
    "Nadpotliwość pachy / dłonie / stopy",
    "Nowość! Toksynaa Relfydess - 2 okolice",
    "Mezobotox",
    "Toksyna botulinowa BOTOX - 3 okolice",
    "Toksyna botulinowa BOTOX - 4 okolice",
    "Toksyna botulinowa BOTOX - Lifting brwi",
    "Nowość! Toksynaa Relfydess - 3 okolice",
    "Toksyna botulinowa BOTOX - Leczenie migreny",
    "Toksyna botulinowa BOTOX - FULL FACE",
    "Modelowanie ust",
    "Kwas hialuronowy - wypełnienie / modelowanie - 1 ampułka",
    "Modelowanie ust \"na płasko\"",
    "Teosyal RHA2 - 1 ampułka",
    "Teosyal Redensity II",
    "Teosyal RHA3 - 1 ampułka",
    "Teosyal Ultradeep - 1 ampułka",
    "Teosyal RHA4 - 1 ampułka",
    "Kwas hialuronowy - wypełnienie / modelowanie - 2 ampułki",
    "Teosyal RHA2 - 2 ampułki",
    "Teosyal RHA3 - 2 ampułki",
    "Kwas hialuronowy - wypełnienie / modelowanie - 3 ampułki",
    "Teosyal Ultradeep - 2 ampullki",
    "Teosyal RHA4 - 2 ampułki",
    "Konsultacja obesitologiczna (leczenie otyłości)",
    "USG jamy brzusznej",
    "USG tarczycy",
    "Konsultacja obesitologiczna + USG tarczycy",
    "Konsultacja obesitologiczna + USG jamy brzusznej",
    "Kolejna wizyta- leczenie otyłości",
    "PAKIET konsultacja+USG jamy brzusznej+USG tarczycy"
  ]
};

export const AMELIA_SERVICE_CATEGORIES: Record<string, string> = {
  "ACNE Rescue Treatment": "PRO XN - Twarz",
  "Antycellulitowy rytuał SPA": "Bez Kategorii",
  "Augumentacja punktu G": "Ginekologia",
  "Badanie histopatologiczne*": "Chirurgia ogólna",
  "Bandaż Arosha + Masaż Antycellulitowy": "Bandaże AROSHA",
  "Bandaże AROSHA + presoterapia": "Bandaże AROSHA",
  "Bandaże Arosha lift plus - ujędrnienie i napięcie": "Bandaże AROSHA",
  "Bandaże Arosha No Drain - terapia drenująca": "Bandaże AROSHA",
  "Biopsja z założeniem szwu chirurgicznego": "Chirurgia ogólna",
  "Blefaroplastyka powiek górnych": "Chirurgia plastyczna",
  "Blefaroplastyka powiek górnych + dolnych + us. przepukliny tłuszczowej": "Chirurgia plastyczna",
  "Blefaroplastyka powiek górnych + lifting brwi": "Chirurgia plastyczna",
  "Blefaroplastyka powiek górnych + usunięcie przepuklin tłuszczowych": "Chirurgia plastyczna",
  "Chirurgiczne usunięcie nowotworu skóry": "Chirurgia ogólna",
  "Chirurgiczne usunięcie nowotworu z plastyka miejscową": "Chirurgia ogólna",
  "Chirurgiczne usunięcie zmiany skórnej - 1 zmiana": "Chirurgia ogólna",
  "Chirurgiczne usunięcie zmiany skórnej - 2-4 zmiany": "Chirurgia ogólna",
  "Chirurgiczne usunięcie zmiany skórnej - 5-7 zmian": "Chirurgia ogólna",
  "Cytologia ginekologiczna": "Ginekologia",
  "Cytologia jednowarstwowa LBC (płynna cytologia)": "Ginekologia",
  "Cytologia płynna + HPV": "Ginekologia",
  "Dermapen + egzosomy (twarz, szyja, dekolt)": "DERMAPEN 4.0",
  "Dermapen + egzosomy (twarz,szyja)": "DERMAPEN 4.0",
  "Dermapen + egzosomy (twarz)": "DERMAPEN 4.0",
  "DERMAPEN 4.0 + Jalupro twarz": "DERMAPEN 4.0",
  "DERMAPEN 4.0 + Jalupro twarz, szyja": "DERMAPEN 4.0",
  "DERMAPEN 4.0 + Jalupro twarz, szyja, dekolt": "DERMAPEN 4.0",
  "Dermapen 4.0 + osocze bogatopłytkowe (twarz + szyja + dekolt + oczy)": "DERMAPEN 4.0",
  "Dermapen 4.0® - cała twarz + koktaajl filorga NCTF": "DERMAPEN 4.0",
  "Dermapen 4.0® - okolice oczu+ koktaajl filorga NCTF": "DERMAPEN 4.0",
  "Dermapen 4.0® - twarz + szyja+ koktaajl filorga NCTF": "DERMAPEN 4.0",
  "Dermapen 4.0® - twarz+ szyja + dekolt+ koktaajl filorga NCTF": "DERMAPEN 4.0",
  "Dermapen 4.0® + medyczny peeling chemiczny - twarz": "DERMAPEN 4.0",
  "Dermapen 4.0® + medyczny peeling chemiczny - twarz + szyja": "DERMAPEN 4.0",
  "Dermapen 4.0® + medyczny peeling chemiczny - twarz + szyja + dekolt": "DERMAPEN 4.0",
  "Dermapen stymulacja wzrostu włosów": "Dermatologia",
  "Dermapen z kwasem tranexamowym (twarz, szyja, dekolt)": "DERMAPEN 4.0",
  "Dermapen z kwasem tranexamowym (twarz, szyja)": "DERMAPEN 4.0",
  "Dermapen z kwasem tranexamowym (twarz)": "DERMAPEN 4.0",
  "Dodatek - Ampułka": "Kosmetologia",
  "Dodatek - Darsonwal jedna okolica": "Kosmetologia",
  "Dodatek - drenaż limfatyczny na nogi": "Kosmetologia",
  "Dodatek - egzosomy Supernova": "Kosmetologia",
  "Dodatek - Henna brwi + regulacja": "Kosmetologia",
  "Dodatek - Hydrafacial wstęp do zabiegu": "Kosmetologia",
  "Dodatek - Maska algowa": "Kosmetologia",
  "Dodatek - Mikrodermabrazja korundowa do": "Kosmetologia",
  "Dodatek - Oczyszczanie manualne": "Kosmetologia",
  "Dodatek - Peeling chemiczny": "Kosmetologia",
  "Dodatek - Peeling kawitacyjny": "Kosmetologia",
  "Dodatek - Regulacja brwi/wąsik/broda": "Kosmetologia",
  "Dodatek - Wapozon (otworzenie porów)": "Kosmetologia",
  "Dr Cyj - Hair Filler": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Dr Pen okolica oczu + peeling": "Zabiegi ANTI-AGING odmłodzenie/ujędrnienie",
  "Dudasteryd - leczenie łysienia androgenowego": "Dermatologia",
  "Ellanse® M - autorska technika Dr Marty": "Autorskie terapie Dr Marty",
  "Ellanse® S - autorska technika Dr Marty": "Autorskie terapie Dr Marty",
  "Fibryna bogatopłytkowa - 1 okolica": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Fibryna bogatopłytkowa - Więcej niż 1 okolica": "Mezoterapia igłowa / Stymulatory tkankowe",
  "GOURI ( płynny polikaprolakton) - 1 ml": "Autorskie terapie Dr Marty",
  "Henna brwi": "Kosmetologia",
  "Henna pudrowa + regulacja brwi": "Bez Kategorii",
  "Henna rzęs": "Kosmetologia",
  "Hialuronidaza": "Autorskie terapie Dr Marty",
  "Hialuronidaza pod kontrolą USG": "Autorskie terapie Dr Marty",
  "Hydrafacial basic - twarz": "Hydrafacial nr 1 w USA ( oczyszczanie wodorowe)",
  "Hydrafacial basic - twarz + szyja": "Hydrafacial nr 1 w USA ( oczyszczanie wodorowe)",
  "Hydrafacial basic - twarz, szyja, dekolt": "Hydrafacial nr 1 w USA ( oczyszczanie wodorowe)",
  "Hydrafacial na plecy": "Hydrafacial nr 1 w USA ( oczyszczanie wodorowe)",
  "HYDRAFACIAL® oryg. oczyszczanie i rewitalizacja - twarz": "Hydrafacial nr 1 w USA ( oczyszczanie wodorowe)",
  "HYDRAFACIAL® oryg. oczyszczanie i rewitalizacja - twarz + szyja": "Hydrafacial nr 1 w USA ( oczyszczanie wodorowe)",
  "HYDRAFACIAL® oryg. oczyszczanie i rewitalizacja - twarz + szyja + dekolt": "Hydrafacial nr 1 w USA ( oczyszczanie wodorowe)",
  "HYDRAFACIAL® z peelingiem kwaoswym GLYSAL - twarz": "Hydrafacial nr 1 w USA ( oczyszczanie wodorowe)",
  "HYDRAFACIAL® z peelingiem kwaoswym GLYSAL - twarz + szyja": "Hydrafacial nr 1 w USA ( oczyszczanie wodorowe)",
  "HYDRAFACIAL® z peelingiem kwaoswym GLYSAL - twarz + szyja + dekolt": "Hydrafacial nr 1 w USA ( oczyszczanie wodorowe)",
  "Icoone drenaż limfatyczny - 1 obszar": "Icoone - zabiegi na ciało",
  "Icoone drenaż limfatyczny - 1 obszar pakiet 10 zabiegów": "Icoone - zabiegi na ciało",
  "Icoone drenaż limfatyczny - 2 obszary": "Icoone - zabiegi na ciało",
  "Icoone drenaż limfatyczny - 2 obszary pakiet 10 zabiegów": "Icoone - zabiegi na ciało",
  "Icoone drenaż limfatyczny - 3 obszary": "Icoone - zabiegi na ciało",
  "Icoone drenaż limfatyczny - 3 obszary pakiet 10 zabiegów": "Icoone - zabiegi na ciało",
  "Icoone drenaż limfatyczny - pakiet 10 zabiegów": "Icoone - zabiegi na ciało",
  "Icoone na twarz (intensywny drenaż liftingujący)": "Icoone - zabiegi na ciało",
  "Iniekcja sterydu": "Dermatologia",
  "Jalupro mezoterapia aminokwasami - Jalupro Classic® 1 ampułka": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Jalupro mezoterapia aminokwasami - Jalupro Classic® 2 ampułki": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Jalupro mezoterapia aminokwasami - Jalupro Classic® 3 ampułki": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Jalupro SUPERHYDRO - 2 amp": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Japoński rytuał młodości masaż KOBIDO + PEELING": "Bez Kategorii",
  "Kolejna wizyta- leczenie otyłości": "Leczenie otyłości",
  "Komplet henna rzęsy + brwi": "Kosmetologia",
  "Konsultacja + usg aorty brzusznej i tętnic": "Chirurgia naczyniowa",
  "Konsultacja + usg doppler kończyn-żył lub tetnic": "Chirurgia naczyniowa",
  "Konsultacja + USG leczenie powikłań": "Konsultacje Specjalistyczne",
  "Konsultacja chirurgiczna": "Chirurgia ogólna",
  "Konsultacja dermatologiczna": "Konsultacje Specjalistyczne",
  "Konsultacja dermatologiczna u Dr Aliny": "Dermatologia",
  "Konsultacja flebologiczna": "Konsultacje Specjalistyczne",
  "Konsultacja ginekologiczna": "Konsultacje Specjalistyczne",
  "Konsultacja ginekologiczna + usg": "Ginekologia",
  "Konsultacja kobiet w ciąży": "Konsultacje Specjalistyczne",
  "Konsultacja kosmetologiczna": "Konsultacje Specjalistyczne",
  "Konsultacja lekarza medycyny estetycznej": "Konsultacje Specjalistyczne",
  "Konsultacja obesitologiczna (leczenie otyłości)": "Leczenie otyłości",
  "Konsultacja obesitologiczna + USG jamy brzusznej": "Leczenie otyłości",
  "Konsultacja obesitologiczna + USG tarczycy": "Leczenie otyłości",
  "Konsultacja trychologiczna": "Dermatologia",
  "Konsultacja z dermatoskopią": "Dermatologia",
  "Konsultacja z dermatoskopią u Dr Aliny": "Dermatologia",
  "Konsultacja z indywidualnie dobranym zabiegiem": "Kosmetologia",
  "Konsultacja z kwalifikacją": "ScarINK – Kompleksowa Terapia",
  "Kontrola": "Konsultacje Specjalistyczne",
  "Ksantohumol Recovery Treatment do zabiegu": "PRO XN - Twarz",
  "Kwas hialuronowy - wypełnienie / modelowanie - 1 ampułka": "Kwas Hialuronowy - wypełnienie / modelowanie",
  "Kwas hialuronowy - wypełnienie / modelowanie - 2 ampułki": "Kwas Hialuronowy - wypełnienie / modelowanie",
  "Kwas hialuronowy - wypełnienie / modelowanie - 3 ampułki": "Kwas Hialuronowy - wypełnienie / modelowanie",
  "Kwas hialuronowy autorska technika Dr Marty - 1 ampułka": "Autorskie terapie Dr Marty",
  "Kwas hialuronowy autorska technika Dr Marty - 2 ampułki": "Autorskie terapie Dr Marty",
  "Kwas hialuronowy autorska technika Dr Marty - 3 ampułki": "Autorskie terapie Dr Marty",
  "Kwas polimlekowy lanluma - modelowanie pośladków": "Autorskie terapie Dr Marty",
  "Kwas polimlekowy lanluma - Modelowanie pośladków": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Kwas polimlekowy lanluma - Twarz": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Kwas polimlekowy lanluma - Twarz + szyja": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Kwas polimlekowy lanluma - Twarz, szyja i dekolt": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Kwas polimlekowy Lanluma pod kontrolą usg (twarz)": "Autorskie terapie Dr Marty",
  "Kwas polimlekowy Lanluma pod kontrolą usg (twarz+szyja)": "Autorskie terapie Dr Marty",
  "Kwas polimlekowy Lanluma pod kontrolą usg (twarz+szyja+dekolt)": "Autorskie terapie Dr Marty",
  "Kwas polimlekowy Lanluma twarz": "Autorskie terapie Dr Marty",
  "Kwas polimlekowy Lanluma twarz i szyja": "Autorskie terapie Dr Marty",
  "Kwas polimlekowy Lanluma twarz, szyja i dekolt": "Autorskie terapie Dr Marty",
  "Labioplastyka": "Ginekologia",
  "Laser tulowy dodatkowy obszar lub przebarwienie": "Laser tulowy",
  "Laser tulowy na dłonie": "Laser tulowy",
  "Laser tulowy na twarz": "Laser tulowy",
  "Laser tulowy twarz + szyja": "Laser tulowy",
  "Laser tulowy twarz + szyja + dekolt": "Laser tulowy",
  "Laserowe usunięcie zmian skórnych - >6 zmian na twarzy": "Chirurgia ogólna",
  "Laserowe usunięcie zmian skórnych - 1-3 zmian na twarzy": "Chirurgia ogólna",
  "Laserowe usunięcie zmian skórnych - 4-6 zmian na twarzy": "Chirurgia ogólna",
  "Laserowe usuwanie żylaków - 1 noga": "Chirurgia naczyniowa",
  "Laserowe usuwanie żylaków - 2 nogi": "Chirurgia naczyniowa",
  "Laserowe zamykanie naczynka - jedno naczynko": "Bez Kategorii",
  "Laserowe zamykanie naczynka - powyżej 3": "Bez Kategorii",
  "Leczenie immunomodulujące - łysienie plackowate": "Dermatologia",
  "Leczenie pochwicy toksyna botulinową": "Ginekologia",
  "Leczenie ran przewlekłych - opracowanie rany": "Chirurgia ogólna",
  "Leczenie ran przewlekłych wraz z konsultacją lek.": "Chirurgia ogólna",
  "Leczenie wysiłkowego nietrzymania moczu": "Ginekologia",
  "Letnie oczyszczanie twarzy": "Kosmetologia",
  "Lifting nićmi APTOS®": "Nici - liftingujące, stymulujące",
  "Lifting podbródka z liposukcją+nici+kwas hialuron.": "Autorskie terapie Dr Marty",
  "Lipoliza iniekcyjna - 1 amp": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Lipotransfer - lifting pośladków": "Chirurgia plastyczna",
  "Lipotransfer - lifting twarzy": "Chirurgia plastyczna",
  "Lipotransfer - powiększanie piersi": "Chirurgia plastyczna",
  "Lipotransfer - powiększenie penisa": "Chirurgia plastyczna",
  "Łyżeczkowanie zmian skórnych": "Dermatologia",
  "Makijaż permanentny brwi": "Makijaż permanentny",
  "Makijaż permanentny ust": "Makijaż permanentny",
  "Manualny drenaż limfatyczny": "Bez Kategorii",
  "Masaż karku i głowy": "Bez Kategorii",
  "Masaż kobido - niechirurgiczny masaż liftingujący": "Bez Kategorii",
  "Masaż MADERO - brazylijski antycellulitowy": "Bez Kategorii",
  "Masaż relaksacyjny twarzy, szyi i dekoltu": "Bez Kategorii",
  "MedEstelle COSMO S-PEEL Vit. C twarz": "MedEstelle - zabiegi bankietowe na twarz",
  "MedEstelle COSMO S-PEEL Vit. C twarz + szyja": "MedEstelle - zabiegi bankietowe na twarz",
  "MedEstelle COSMO S-PEEL Vit. C twarz + szyja + dekolt": "MedEstelle - zabiegi bankietowe na twarz",
  "MedEstelle Redness Sendo Calm Premium - twarz": "MedEstelle - zabiegi bankietowe na twarz",
  "MedEstelle Redness Sendo Calm Premium twarz+szyja": "MedEstelle - zabiegi bankietowe na twarz",
  "MedEstelle Redness Senso Calm Premium twarz + szyja + dekolt": "MedEstelle - zabiegi bankietowe na twarz",
  "MedEstelle Senso Super Hydra Premium twarz": "MedEstelle - zabiegi bankietowe na twarz",
  "MedEstelle Senso Super Hydra Premium twarz + szyja": "MedEstelle - zabiegi bankietowe na twarz",
  "MedEstelle Senso Super Hydra Premium twarz + szyja + dekolt": "MedEstelle - zabiegi bankietowe na twarz",
  "Medyczny peeling skóry głowy": "Kosmetologia",
  "Mezobotox": "Toksyna botulinowa BOTOX - likwidacja zmarszczek",
  "Mezoterapia mezokoktajlami - okolice oczu": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Mezoterapia mezokoktajlami - Skóra głowy": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Mezoterapia mezokoktajlami - Twarz": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Mezoterapia mezokoktajlami - Twarz + szyja": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Mezoterapia mezokoktajlami - Twarz + szyja + dekolt": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Mezoterapia mezokoktajlami - Wybrany obszar": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Mezoterapia Neuvia HYDRO de lux Twarz+szyja 2,5ml": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Męski rytuał pielęgnacyjny": "Kosmetologia",
  "Micropeel": "ScarINK – Kompleksowa Terapia",
  "Miniflebektomia": "Chirurgia naczyniowa",
  "Modelowanie ust": "Kwas Hialuronowy - wypełnienie / modelowanie",
  "Modelowanie ust \"na płasko\"": "Kwas Hialuronowy - wypełnienie / modelowanie",
  "Modelowanie ust autorską techniką Dr Marty": "Autorskie terapie Dr Marty",
  "Nacięcie i drenaż ropnia": "Chirurgia ogólna",
  "Nadpotliwość okolic pachwin i sromu": "Ginekologia",
  "Nadpotliwość pachy / dłonie / stopy": "Toksyna botulinowa BOTOX - likwidacja zmarszczek",
  "NANOSOFT EYES BOOSTERS": "Mezoterapia igłowa / Stymulatory tkankowe",
  "NCTF135 HA Filorga": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Nici stymulujące 20 szt": "Nici - liftingujące, stymulujące",
  "Nici z kwasu polimlekowego (haczykowe) - 4 nitki": "Nici - liftingujące, stymulujące",
  "Nici z kwasu polimlekowego (haczykowe) - dodatkowa nitka": "Nici - liftingujące, stymulujące",
  "Nowość! GOURI PCL ( polikaprolakton) - 1ml": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Nowość! Toksynaa Relfydess - 1 okolica": "Toksyna botulinowa BOTOX - likwidacja zmarszczek",
  "Nowość! Toksynaa Relfydess - 2 okolice": "Toksyna botulinowa BOTOX - likwidacja zmarszczek",
  "Nowość! Toksynaa Relfydess - 3 okolice": "Toksyna botulinowa BOTOX - likwidacja zmarszczek",
  "Oczyszczanie manualne z peelingiem kwasowym": "Kosmetologia",
  "Odmładzanie z mikronakłuwaniem - twarz + szyja": "Zabiegi ANTI-AGING odmłodzenie/ujędrnienie",
  "Odmładzanie z mikronakłuwaniem - twarz + szyja + dekolt": "Zabiegi ANTI-AGING odmłodzenie/ujędrnienie",
  "Osocze bogatopłytkowe PRP - Skóra głowy": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Osocze bogatopłytkowe PRP - Twarz": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Osocze bogatopłytkowe PRP - Twarz + szyja": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Osocze bogatopłytkowe PRP - Twarz + szyja + dekolt": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Osocze bogatopłytkowe PRP - Wybrany obszar": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Pakiet 10 zabiegów masaż MADERO": "Bez Kategorii",
  "Pakiet 3 zabiegi RF okolica oczu": "Radiofrekwencja mikroigłowa RF",
  "Pakiet 3 zabiegi RF twarz": "Radiofrekwencja mikroigłowa RF",
  "Pakiet 3 zabiegi RF twarz + szyja dekolt": "Radiofrekwencja mikroigłowa RF",
  "PAKIET konsultacja+USG jamy brzusznej+USG tarczycy": "Leczenie otyłości",
  "Peeling fenolowy na twarz": "Dermatologia",
  "Peeling kawitacyjny z doczyszczaniem manualnym": "Kosmetologia",
  "Peeling kawitacyjny z peelingiem kwasowym": "Kosmetologia",
  "Peeling MEDIDERMA® 3-Retises Ct Yellow - twarz + szyja": "MEDIDERMA - zabiegi na twarz",
  "Peeling MEDIDERMA® 3-Retises Ct Yellow - twarz + szyja + dekolt": "MEDIDERMA - zabiegi na twarz",
  "Peeling MEDIDERMA® 3-Retises Ct Yellow - twarz/dekolt/plecy": "MEDIDERMA - zabiegi na twarz",
  "Peeling MEDIDERMA® bankietowy liftingujący - twarz + szyja": "MEDIDERMA - zabiegi na twarz",
  "Peeling MEDIDERMA® bankietowy liftingujący - twarz + szyja + dekolt": "MEDIDERMA - zabiegi na twarz",
  "Peeling MEDIDERMA® bankietowy liftingujący - twarz/plecy/dekolt": "MEDIDERMA - zabiegi na twarz",
  "Peeling MEDIDERMA® bankietowy odświeżający - twarz + szyja": "MEDIDERMA - zabiegi na twarz",
  "Peeling MEDIDERMA® bankietowy odświeżający - twarz + szyja + dekolt": "MEDIDERMA - zabiegi na twarz",
  "Peeling MEDIDERMA® bankietowy odświeżający - twarz/dekolt/plecy": "MEDIDERMA - zabiegi na twarz",
  "Peeling MEDIDERMA® Bankietowy z wit.C - twarz + szyja": "MEDIDERMA - zabiegi na twarz",
  "Peeling MEDIDERMA® Bankietowy z wit.C - twarz + szyja + dekolt": "MEDIDERMA - zabiegi na twarz",
  "Peeling MEDIDERMA® Bankietowy z wit.C - twarz/plecy/dekolt": "MEDIDERMA - zabiegi na twarz",
  "Peeling MEDIDERMA® Podstawowy Azelac - twarz + szyja": "MEDIDERMA - zabiegi na twarz",
  "Peeling MEDIDERMA® Podstawowy Azelac - twarz + szyja + dekolt": "MEDIDERMA - zabiegi na twarz",
  "Peeling MEDIDERMA® Podstawowy Azelac - twarz/plecy/dekolt": "MEDIDERMA - zabiegi na twarz",
  "Peeling MEDIDERMA® Podstawowy DNA Recovery - twarz + szyja": "MEDIDERMA - zabiegi na twarz",
  "Peeling MEDIDERMA® Podstawowy DNA Recovery - twarz + szyja + dekolt": "MEDIDERMA - zabiegi na twarz",
  "Peeling MEDIDERMA® Podstawowy DNA Recovery - twarz/plecy/dekolt": "MEDIDERMA - zabiegi na twarz",
  "Peeling MEDIDERMA® Podstawowy Ferulac System - twarz + szyja": "MEDIDERMA - zabiegi na twarz",
  "Peeling MEDIDERMA® Podstawowy Ferulac System - twarz + szyja + dekolt": "MEDIDERMA - zabiegi na twarz",
  "Peeling MEDIDERMA® Podstawowy Ferulac System - twarz/plecy/dekolt": "MEDIDERMA - zabiegi na twarz",
  "Peeling MEDIDERMA® Podstawowy Ferulac Valencia - twarz + szyja": "MEDIDERMA - zabiegi na twarz",
  "Peeling MEDIDERMA® Podstawowy Ferulac Valencia - twarz + szyja + dekolt": "MEDIDERMA - zabiegi na twarz",
  "Peeling MEDIDERMA® Podstawowy Ferulac Valencia - twarz/plecy/dekolt": "MEDIDERMA - zabiegi na twarz",
  "Peeling medyczny twarz+szyja": "Kosmetologia",
  "Peeling TCA Pain Control®": "Autorskie terapie Dr Marty",
  "Plastyka blizny": "Chirurgia plastyczna",
  "Plastyka powiek dolnych": "Chirurgia plastyczna",
  "Plastyka powiek górnych": "Autorskie terapie Dr Marty",
  "Plastyka powiek górnych + usunięcie tłuszczu + lifting brwi": "Autorskie terapie Dr Marty",
  "Plastyka powiek górnych + usunięcie tłuszczu z przegrody oczodołu": "Autorskie terapie Dr Marty",
  "Podcinanie blizn po trądziku autorską technika": "Autorskie terapie Dr Marty",
  "Powtórzenie recepty": "Konsultacje Specjalistyczne",
  "PRO XN Zabieg rozświetlający BrightUp": "PRO XN - Twarz",
  "PRO XN® Przeciwstarzeniowy I stopień": "PRO XN - Twarz",
  "PRO XN® Przeciwstarzeniowy II stopień z retinolem": "PRO XN - Twarz",
  "PRO XN® Przeciwstarzeniowy III stopień + Dermapen": "PRO XN - Twarz",
  "PROFHILO BODY": "Mezoterapia igłowa / Stymulatory tkankowe",
  "PROFHILO STRUCTURA": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Recepcja": "Recepcja",
  "Regulacja Brwi": "Bez Kategorii",
  "Relaksacyjny masaż całego ciała": "Bez Kategorii",
  "Relaksacyjny masaż pleców": "Bez Kategorii",
  "Rewitalizacja pochwy PRP": "Ginekologia",
  "Rewitalizujące nici PDO autorska technika -20 nici": "Autorskie terapie Dr Marty",
  "RF Radiofrekwencja mikroigłowa - Okolica oczu": "Radiofrekwencja mikroigłowa RF",
  "RF Radiofrekwencja mikroigłowa - szyja": "Radiofrekwencja mikroigłowa RF",
  "RF Radiofrekwencja mikroigłowa - twarz": "Radiofrekwencja mikroigłowa RF",
  "RF Radiofrekwencja mikroigłowa - twarz + szyja": "Radiofrekwencja mikroigłowa RF",
  "RF Radiofrekwencja mikroigłowa - twarz + szyja + dekolt": "Radiofrekwencja mikroigłowa RF",
  "ScarInk Mikronakłuwanie": "ScarINK – Kompleksowa Terapia",
  "Skleroterapia": "Chirurgia naczyniowa",
  "Specjalistyczna konsultacja u Dr Marty": "Autorskie terapie Dr Marty",
  "Stymulator tkankowy Jalupro Classic + Jalupro HMW": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Stymulator tkankowy Jalupro HMW": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Stymulator tkankowy Jalupro HMW 2 amp": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Stymulator tkankowy Jalupro SuperHydro®": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Stymulator tkankowy Jalupro Young Eye®": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Stymulator tkankowy Pluryal Silk u lekarzy": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Stymulator tkankowy Pluryal Silk u P. Magdy": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Stymulator tkankowy Prophilo - molekuła młodości": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Stymulator tkankowy Radiesse - 1 ampułka": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Stymulator tkankowy Radiesse - 2 ampułki": "Mezoterapia igłowa / Stymulatory tkankowe",
  "SUNEKOS 1200": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Sunekos 200": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Supernova Nebula ACTO2 10%": "Nebula",
  "Supernowa Nebula Acto2 Orion Strong": "Bez Kategorii",
  "Tapping twarzy": "Bez Kategorii",
  "Teosyal Redensity II": "Kwas Hialuronowy - wypełnienie / modelowanie",
  "Teosyal RHA2 - 1 ampułka": "Kwas Hialuronowy - wypełnienie / modelowanie",
  "Teosyal RHA2 - 2 ampułki": "Kwas Hialuronowy - wypełnienie / modelowanie",
  "Teosyal RHA3 - 1 ampułka": "Kwas Hialuronowy - wypełnienie / modelowanie",
  "Teosyal RHA3 - 2 ampułki": "Kwas Hialuronowy - wypełnienie / modelowanie",
  "Teosyal RHA4 - 1 ampułka": "Kwas Hialuronowy - wypełnienie / modelowanie",
  "Teosyal RHA4 - 2 ampułki": "Kwas Hialuronowy - wypełnienie / modelowanie",
  "Teosyal Ultradeep - 1 ampułka": "Kwas Hialuronowy - wypełnienie / modelowanie",
  "Teosyal Ultradeep - 2 ampullki": "Kwas Hialuronowy - wypełnienie / modelowanie",
  "Terapia blizn - Dr Pen + peeling chemiczny Twarz": "Zabiegi ANTI-AGING odmłodzenie/ujędrnienie",
  "Terapia blizny - Dr Pen + egzosomy": "Zabiegi ANTI-AGING odmłodzenie/ujędrnienie",
  "Toksyna botulinowa - 1 okolica": "Autorskie terapie Dr Marty",
  "Toksyna botulinowa - 2 okolice": "Autorskie terapie Dr Marty",
  "Toksyna botulinowa - 3 okolice": "Autorskie terapie Dr Marty",
  "Toksyna botulinowa - 4 okolice": "Autorskie terapie Dr Marty",
  "Toksyna botulinowa - Full Face": "Autorskie terapie Dr Marty",
  "Toksyna botulinowa - Leczenie bruksizmu": "Autorskie terapie Dr Marty",
  "Toksyna botulinowa - Leczenie migreny": "Autorskie terapie Dr Marty",
  "Toksyna botulinowa - Leczenie nadpotliwości pachy / dłonie / stopy": "Autorskie terapie Dr Marty",
  "Toksyna botulinowa - Lifting brwi": "Autorskie terapie Dr Marty",
  "Toksyna botulinowa - Lip Flip / broda brukowana / uniesienie kącików ust": "Autorskie terapie Dr Marty",
  "Toksyna botulinowa - Redukcja uśmiechu dziąsłowego": "Autorskie terapie Dr Marty",
  "Toksyna botulinowa - Zwężenie płatków nosa / podniesienie czubka nosa": "Autorskie terapie Dr Marty",
  "Toksyna botulinowa BOTOX - 1 okolica": "Toksyna botulinowa BOTOX - likwidacja zmarszczek",
  "Toksyna botulinowa BOTOX - 2 okolice": "Toksyna botulinowa BOTOX - likwidacja zmarszczek",
  "Toksyna botulinowa BOTOX - 3 okolice": "Toksyna botulinowa BOTOX - likwidacja zmarszczek",
  "Toksyna botulinowa BOTOX - 4 okolice": "Toksyna botulinowa BOTOX - likwidacja zmarszczek",
  "Toksyna botulinowa BOTOX - Bruksizm": "Toksyna botulinowa BOTOX - likwidacja zmarszczek",
  "Toksyna botulinowa BOTOX - FULL FACE": "Toksyna botulinowa BOTOX - likwidacja zmarszczek",
  "Toksyna botulinowa BOTOX - Leczenie migreny": "Toksyna botulinowa BOTOX - likwidacja zmarszczek",
  "Toksyna botulinowa BOTOX - Lifting brwi": "Toksyna botulinowa BOTOX - likwidacja zmarszczek",
  "Toksyna botulinowa BOTOX - Lip flip / broda brukowana / uniesienie kącika ust": "Toksyna botulinowa BOTOX - likwidacja zmarszczek",
  "Toksyna botulinowa BOTOX - Redukcja uśmiechu dziąsłowego": "Toksyna botulinowa BOTOX - likwidacja zmarszczek",
  "Toksyna botulinowa BOTOX - Zwężenie płatków nosa / podniesienie czubka nosa": "Toksyna botulinowa BOTOX - likwidacja zmarszczek",
  "Topilase® - bezbolesna hialuronidaza w kremie": "Autorskie terapie Dr Marty",
  "Tropokolagen GUNA - 1 ampułka": "Tropokolagen GUNA",
  "Tropokolagen GUNA - 2 ampułki": "Tropokolagen GUNA",
  "Tropokolagen GUNA - 3 ampułki": "Tropokolagen GUNA",
  "TwAc EYES": "Mezoterapia igłowa / Stymulatory tkankowe",
  "USG ginekologiczne": "Ginekologia",
  "USG jamy brzusznej": "Leczenie otyłości",
  "USG tarczycy": "Leczenie otyłości",
  "USG wczesna ciąża": "Ginekologia",
  "Usunięcie kępek żółtych": "Chirurgia plastyczna",
  "Usuwanie zmian w okolicy oczu": "Chirurgia plastyczna",
  "Uwrażliwienie łechtaczki kwasem hialuronowym": "Ginekologia",
  "Wolumetria twarzy - autorską techniką dr Marty": "Autorskie terapie Dr Marty",
  "Wypełnianie zmarszczek- autorska technika Dr Marty": "Autorskie terapie Dr Marty",
  "Xela Rederm 1,1% - 1 ampułka": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Xela Rederm 1,1% - 2 ampułki": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Xela Rederm 2,2% - 1 ampułka": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Xela Rederm 2,2% - 2 ampułki": "Mezoterapia igłowa / Stymulatory tkankowe",
  "Zabieg nawilżający na twarz": "Kosmetologia",
  "Założenie wkładki hormonalnej": "Ginekologia",
  "Założenie wkładki niehormonalnej": "Ginekologia"
};
